/* ============ Catalogue & seed data ============ */
const CATS0=[{id:'pizza',name:'Pizza',emoji:'🍕'},{id:'burgers',name:'Burgers',emoji:'🍔'},{id:'fries',name:'Fries',emoji:'🍟'},{id:'wraps',name:'Wraps',emoji:'🌯'},{id:'sides',name:'Sides',emoji:'🍗'},{id:'beverages',name:'Beverages',emoji:'🥤'},{id:'desserts',name:'Desserts',emoji:'🍫'},{id:'combos',name:'Combos',emoji:'🎁'}];
const P=(id,name,cat,veg,price,mrp,spice,rating,rev,tag,stock,desc,ing,art,cust,dpat)=>({id,name,cat,veg,price,mrp:mrp||price,spice,rating,rev,tag,stock,desc,ing,art,cust:cust||'',dpat:dpat||'',sold:Math.round(rev*(2.6+(hash(id)%9)/10)),created:0,oos:false,bestseller:tag==='best'});
const PRODUCTS0=[
P('p1','Margherita Classic','pizza',1,199,249,0,4.6,1284,'best',40,'San Marzano tomato sauce, fresh mozzarella and basil on a hand-stretched base.',['Tomato sauce','Fresh mozzarella','Basil','Olive oil'],['pizza','margherita'],'pizza'),
P('p2','Farmhouse Feast','pizza',1,279,329,0,4.5,960,'',36,'Capsicum, onion, olives, sweet corn and mushrooms under a blanket of mozzarella.',['Capsicum','Onion','Black olives','Sweet corn','Mushroom','Mozzarella'],['pizza','veg'],'pizza'),
P('p3','Paneer Tikka Blast','pizza',1,299,349,2,4.7,1120,'best',28,'Tandoor-spiced paneer, onion and coriander on a smoky makhani sauce.',['Tandoori paneer','Onion','Coriander','Makhani sauce','Mozzarella'],['pizza','paneer'],'pizza'),
P('p4','Pepperoni Inferno','pizza',0,349,419,2,4.8,1876,'best',30,'Double-layer chicken pepperoni, chilli flakes and a hot honey drizzle.',['Chicken pepperoni','Mozzarella','Chilli flakes','Hot honey'],['pizza','pepperoni'],'pizza'),
P('p5','BBQ Chicken Smoke','pizza',0,339,0,1,4.6,802,'',32,'Smoked chicken, red onion and coriander with a sticky BBQ swirl.',['Smoked chicken','Red onion','BBQ sauce','Coriander','Mozzarella'],['pizza','bbq'],'pizza'),
P('p6','Chicken Tikka Supreme','pizza',0,359,399,2,4.5,743,'',26,'Charred chicken tikka, capsicum and onion with mint-yoghurt drizzle.',['Chicken tikka','Capsicum','Onion','Mint yoghurt','Mozzarella'],['pizza','chicken'],'pizza'),
P('p7','Four Cheese Melt','pizza',1,329,0,0,4.7,512,'new',5,'Mozzarella, cheddar, parmesan and cream cheese finished with garlic oregano oil.',['Mozzarella','Cheddar','Parmesan','Cream cheese','Garlic oil'],['pizza','cheese'],'pizza'),
P('p8','Peri-Peri Veggie','pizza',1,289,0,3,4.4,388,'new',30,'Fiery peri-peri sauce, jalapeños, capsicum and onion for heat seekers.',['Peri-peri sauce','Jalapeño','Capsicum','Onion','Mozzarella'],['pizza','peri'],'pizza'),
P('b1','Classic Aloo Smash','burgers',1,129,149,1,4.5,2140,'best',60,'Crisp aloo-pea patty, lettuce, tomato and house mayo in a toasted brioche bun.',['Aloo-pea patty','Brioche bun','Lettuce','Tomato','House mayo'],['burger','aloo'],'burger','aloo'),
P('b2','Crispy Chicken Zinger','burgers',0,179,209,2,4.8,2890,'best',55,'Buttermilk-fried chicken thigh, pickles, slaw and fiery zinger sauce.',['Fried chicken thigh','Pickles','Slaw','Zinger sauce','Brioche bun'],['burger','chicken'],'burger','cchick'),
P('b3','Double Smash Cheese','burgers',0,249,289,0,4.7,1523,'best',40,'Two smashed chicken patties, molten cheddar, caramelised onion and burger sauce.',['2 chicken patties','Cheddar','Caramelised onion','Burger sauce'],['burger','beef','dbl'],'burger','cchick'),
P('b4','Paneer Crunch','burgers',1,159,0,1,4.4,877,'',34,'Panko-crusted paneer slab, mint mayo, onion rings and crunchy lettuce.',['Paneer slab','Mint mayo','Onion rings','Lettuce'],['burger','paneer'],'burger','panpat'),
P('b5','Peri-Peri Chicken Stack','burgers',0,199,0,3,4.6,652,'new',30,'Spiced chicken fillet, peri-peri glaze, jalapeños and cooling coleslaw.',['Chicken fillet','Peri-peri glaze','Jalapeño','Coleslaw'],['burger','spicy'],'burger','cchick'),
P('b6','Mushroom Swiss','burgers',1,189,0,0,4.3,410,'',4,'Garlic-butter mushroom patty, melted Swiss-style cheese and fresh rocket.',['Mushroom patty','Swiss-style cheese','Rocket','Garlic butter'],['burger','mushroom'],'burger','mush'),
P('b7','Veggie Volcano','burgers',1,149,0,3,4.5,296,'',30,'Spicy bean and corn patty, jalapeños, chipotle mayo and pepper-jack.',['Bean-corn patty','Jalapeño','Chipotle mayo','Pepper-jack'],['burger','veg'],'burger','bean'),
P('f1','Classic Salted Fries','fries',1,89,109,0,4.5,3120,'best',80,'Skin-on fries, twice-fried until golden and finished with sea salt.',['Potato','Sea salt'],['fries','classic']),
P('f2','Peri-Peri Fries','fries',1,109,0,1,4.6,2011,'',70,'Crisp fries tossed in smoky peri-peri seasoning with a garlic dip.',['Potato','Peri-peri spice','Garlic dip'],['fries','peri']),
P('f3','Cheesy Loaded Fries','fries',1,149,179,0,4.8,1740,'best',50,'Fries smothered in cheddar sauce, jalapeños and chives.',['Potato','Cheddar sauce','Jalapeño','Chives'],['fries','loaded']),
P('f4','Masala Wedges','fries',1,119,0,1,4.3,634,'',45,'Thick potato wedges dusted in chaat masala with mint chutney.',['Potato wedges','Chaat masala','Mint chutney'],['fries','wedges']),
P('w1','Paneer Tikka Wrap','wraps',1,139,0,1,4.4,540,'',40,'Grilled paneer tikka, pickled onion and mint chutney in a flaky paratha wrap.',['Paneer tikka','Pickled onion','Mint chutney','Paratha'],['wrap','v']),
P('w2','Chicken Kathi Roll','wraps',0,159,0,2,4.6,910,'best',40,'Egg-wash paratha rolled with spiced chicken, onion and green chutney.',['Chicken','Egg paratha','Onion','Green chutney'],['wrap','nv']),
P('w3','Crispy Veg Wrap','wraps',1,119,0,0,4.2,322,'',40,'Crunchy veg patty, shredded cabbage and tangy schezwan mayo.',['Veg patty','Cabbage','Schezwan mayo','Tortilla'],['wrap','v']),
P('w4','Chicken Caesar Wrap','wraps',0,169,0,0,4.3,201,'new',30,'Grilled chicken, romaine, parmesan and creamy Caesar dressing.',['Grilled chicken','Romaine','Parmesan','Caesar dressing'],['wrap','nv']),
P('s1','Garlic Bread with Cheese','sides',1,119,139,0,4.7,2310,'best',60,'Toasted baguette slices with garlic butter and molten mozzarella.',['Baguette','Garlic butter','Mozzarella','Parsley'],['side','garlic']),
P('s2','Crispy Chicken Nuggets (6 pc)','sides',0,149,0,0,4.5,1480,'',50,'Golden nuggets made from whole chicken breast with a honey-mustard dip.',['Chicken breast','Herb crumb','Honey-mustard dip'],['side','nuggets']),
P('s3','Onion Rings','sides',1,109,0,0,4.3,690,'',40,'Beer-battered onion rings, fried until crisp with smoky ketchup.',['Onion','Batter','Smoky ketchup'],['side','rings']),
P('s4','Jalapeño Cheese Poppers','sides',1,139,0,1,4.6,402,'new',30,'Crisp crumb-coated bites bursting with cream cheese and jalapeño.',['Cream cheese','Jalapeño','Herb crumb'],['side','poppers']),
P('s5','Smoky Chicken Wings (6 pc)','sides',0,189,0,2,4.6,780,'',3,'Oven-roasted wings glazed in smoky chilli sauce with ranch dip.',['Chicken wings','Smoky chilli glaze','Ranch dip'],['side','wings']),
P('d1','Coke 300 ml','beverages',1,49,0,0,4.6,4200,'',200,'Ice-cold Coca-Cola, served in a 300 ml glass bottle.',['Carbonated drink'],['cup','cola']),
P('d2','Cold Coffee','beverages',1,119,139,0,4.5,1210,'',60,'Slow-brewed coffee blended with milk, ice and a swirl of cream.',['Coffee','Milk','Ice cream','Cream'],['cup','coffee']),
P('d3','Virgin Mojito','beverages',1,99,0,0,4.5,860,'',60,'Fresh mint, lime and crushed ice topped with soda.',['Mint','Lime','Soda','Crushed ice'],['cup','mojito']),
P('d4','Alphonso Mango Shake','beverages',1,129,0,0,4.6,470,'new',40,'Thick shake blended from Alphonso mango pulp and chilled milk.',['Alphonso mango','Milk','Ice cream'],['cup','mango']),
P('d5','Fresh Lime Soda','beverages',1,79,0,0,4.2,530,'',60,'Sweet, salted or mixed — served with plenty of ice.',['Lime','Soda','Sugar syrup'],['cup','lime']),
P('t1','Choco Lava Cake','desserts',1,99,0,0,4.8,2050,'best',50,'Warm dark-chocolate cake with a molten centre.',['Dark chocolate','Butter','Eggs'],['dessert','lava']),
P('t2','Brownie Sundae','desserts',1,149,0,0,4.7,940,'',40,'Fudgy walnut brownie topped with vanilla ice cream and hot chocolate sauce.',['Brownie','Vanilla ice cream','Chocolate sauce'],['dessert','brownie']),
P('t3','Cinnamon Churros','desserts',1,119,0,0,4.4,310,'new',2,'Crisp churros rolled in cinnamon sugar with a warm chocolate dip.',['Churros','Cinnamon sugar','Chocolate dip'],['dessert','churros']),
P('t4','Molten Cheesecake Jar','desserts',1,129,0,0,4.3,188,'',30,'Baked cheesecake layered with biscuit crumb and strawberry compote.',['Cream cheese','Biscuit','Strawberry compote'],['dessert','sundae']),
P('c1','Solo Feast','combos',0,229,267,1,4.7,1620,'best',40,'Crispy Chicken Burger + Classic Fries + Coke. The lunchtime favourite.',['Crispy chicken burger','Classic fries','Coke 300 ml'],['combo','solo']),
P('c2','Pizza + Garlic Bread + Coke','combos',1,329,397,0,4.6,880,'',30,'Medium Margherita, cheesy garlic bread and a chilled Coke.',['Medium Margherita','Garlic bread','Coke 300 ml'],['combo','pizza']),
P('c3',"Couple's Combo",'combos',1,699,848,0,4.8,1210,'best',25,'Two medium veg pizzas, garlic bread and two Cokes for date night.',['2 medium pizzas','Garlic bread','2 Coke'],['combo','couple']),
P('c4','Family Feast Box','combos',0,1199,1503,1,4.9,640,'',6,'Two large pizzas, two burgers, loaded fries, wings and four Cokes. Feeds 4–5.',['2 large pizzas','2 burgers','Loaded fries','Wings','4 Coke'],['combo','family']),
P('c5','Student Meal Deal','combos',1,149,187,0,4.5,2280,'new',60,'Aloo Smash burger, classic fries and a Coke at a pocket-friendly price.',['Aloo burger','Classic fries','Coke 300 ml'],['combo','solo']),
P('c6','Burger Duo','combos',0,329,388,1,4.6,570,'',35,'Two crispy chicken burgers with two portions of fries.',['2 chicken burgers','2 fries'],['combo','duo'])
];
PRODUCTS0.forEach(p=>{if(p.id==='c5'||p.id==='c1')p.spice=p.spice});
/* Customisation options */
const OPT={
pizza:{size:{label:'Size',type:'one',items:[['S','Small 7″','Serves 1',0],['M','Medium 9″','Serves 2',130],['L','Large 12″','Serves 3–4',260]],def:'S'},
 crust:{label:'Crust',type:'one',items:[['reg','Classic hand-tossed','',0],['thin','Thin & crispy','',0],['cb','Cheese burst','Molten cheese in the rim',79]],def:'reg'},
 xc:{label:'Extra cheese',type:'toggle',price:49,sub:'A generous extra layer of mozzarella'},
 tops:{label:'Extra toppings',type:'many',items:[['jal','Jalapeños','',30],['oli','Black olives','',30],['mush','Mushrooms','',40],['corn','Sweet corn','',30],['pan','Paneer cubes','',60],['chk','Grilled chicken','',70,'nv']]},
 sauces:{label:'Sauces & dips',type:'many',items:[['garlic','Garlic mayo dip','',20],['peri','Peri-peri dip','',20],['chip','Chipotle dip','',25],['ranch','Ranch dip','',20],['bbq','Smoky BBQ dip','',20]]}},
burger:{patty:{label:'Patty type',type:'one',items:{v:[['aloo','Aloo-pea','',0],['panpat','Paneer slab','',20],['mush','Mushroom','',25],['bean','Spicy bean','',0]],n:[['cchick','Crispy chicken','',0],['gchick','Grilled chicken','',10]]}},
 count:{label:'Patties',type:'one',items:[['1','Single patty','',0],['2','Double patty','Twice the stack',70]],def:'1'},
 cheese:{label:'Cheese',type:'one',items:[['none','No cheese','',0],['slice','Cheddar slice','',25],['double','Double cheese','',45]],def:'none'},
 tops:{label:'Extra toppings',type:'many',items:[['let','Lettuce','',15],['tom','Tomato','',15],['onr','Onion rings','',25],['jal','Jalapeños','',20],['cao','Caramelised onion','',25],['pic','Pickles','',15]]},
 sauces:{label:'Sauces',type:'many',items:[['mayo','House mayo','',10],['mint','Mint mayo','',10],['peri','Peri-peri','',10],['chip','Chipotle','',10],['bbq','Smoky BBQ','',10],['must','Honey mustard','',10]]},
 adds:{label:'Add-ons',type:'many',items:[['fries','Small fries','',69],['coke','Coke 300 ml','',45],['rings','Onion rings','',59]]}}};
function optItems(p,key){const g=OPT[p.cust][key];if(key==='patty')return g.items[p.veg?'v':'n'];let it=g.items.filter(i=>!i[4]||(i[4]==='nv'&&!p.veg));if(key==='tops')it=it.concat((S.xtops||[]).filter(t=>t.cust===p.cust).map(t=>[t.id,t.name,'',t.price]));return it}
function defSel(p){if(p.cust==='pizza')return{size:'S',crust:'reg',xc:0,tops:[],sauces:[]};if(p.cust==='burger')return{patty:p.dpat,count:'1',cheese:'none',tops:[],sauces:[],adds:[]};return null}
function selPrice(p,sel){let t=0;if(!sel)return 0;const g=OPT[p.cust];for(const k in g){const o=g[k];if(o.type==='toggle'){if(sel[k])t+=o.price}else if(o.type==='one'){const it=optItems(p,k).find(i=>i[0]===sel[k]);if(it)t+=it[3]}else{(sel[k]||[]).forEach(v=>{const it=optItems(p,k).find(i=>i[0]===v);if(it)t+=it[3]})}}return t}
function selSummary(p,sel){if(!sel)return'';const g=OPT[p.cust],out=[];for(const k in g){const o=g[k];if(o.type==='toggle'){if(sel[k])out.push(o.label)}else if(o.type==='one'){const it=optItems(p,k).find(i=>i[0]===sel[k]);if(it&&(k==='size'||k==='patty'||it[3]>0||(k==='count'&&sel[k]!=='1')))out.push(it[1].replace(/ [0-9]+″/,''))}else(sel[k]||[]).forEach(v=>{const it=optItems(p,k).find(i=>i[0]===v);if(it)out.push('+'+it[1])})}return out.join(' · ')}
/* Offers (bundles) */
const OFFERS=[
{id:'o1',cat:'today',title:'Flash Feast',badge:'Today only',desc:'Medium Margherita, cheesy garlic bread and two chilled Cokes.',inc:'Medium Margherita · Garlic Bread · 2 Coke',orig:546,price:399,art:['combo','pizza'],ends:'day'},
{id:'o2',cat:'today',title:'Snack Attack',badge:'Limited',desc:'Loaded fries, six nuggets and a Coke to share.',inc:'Cheesy Loaded Fries · Nuggets (6) · Coke',orig:347,price:249,art:['side','nuggets'],ends:'3h'},
{id:'o3',cat:'pizza',title:'Pizza Duo',badge:'Save ₹147',desc:'Margherita and Paneer Tikka small pizzas with two Cokes.',inc:'Small Margherita · Small Paneer Tikka · 2 Coke',orig:596,price:449,art:['combo','couple'],ends:'day'},
{id:'o4',cat:'pizza',title:'Meat Lovers Pair',badge:'Bestseller',desc:'Medium Pepperoni Inferno and Medium BBQ Chicken Smoke.',inc:'Medium Pepperoni Inferno · Medium BBQ Chicken',orig:948,price:749,art:['pizza','pepperoni'],ends:'wk'},
{id:'o5',cat:'burger',title:'Burger Bros',badge:'Save ₹135',desc:'Two Crispy Chicken Zingers, two fries and two Cokes.',inc:'2 Zinger · 2 Classic Fries · 2 Coke',orig:634,price:499,art:['combo','duo'],ends:'day'},
{id:'o6',cat:'burger',title:'Green Stack',badge:'Veg pick',desc:'Paneer Crunch, Aloo Smash, fries and two Cokes.',inc:'Paneer Crunch · Aloo Smash · Fries · 2 Coke',orig:475,price:379,art:['burger','paneer'],ends:'wk'},
{id:'o7',cat:'family',title:'Family Feast (serves 4)',badge:'Best value',desc:'Two large pizzas, garlic bread, wings and four Cokes.',inc:'Large Farmhouse · Large Pepperoni · Garlic Bread · Wings · 4 Coke',orig:1652,price:1299,art:['combo','family'],ends:'wk'},
{id:'o8',cat:'family',title:'Party Box (serves 6)',badge:'Feeds a crowd',desc:'Three medium pizzas, nuggets, wings and four Cokes.',inc:'3 Medium Pizzas · Nuggets (6) · Wings (6) · 4 Coke',orig:1914,price:1499,art:['combo','family'],ends:'wk'},
{id:'o9',cat:'student',title:'Campus Combo',badge:'Student ID',desc:'Aloo Smash, fries and Coke. Show your student ID on delivery or pickup.',inc:'Aloo Smash · Classic Fries · Coke',orig:267,price:149,art:['combo','solo'],ends:'wk'},
{id:'o10',cat:'student',title:'Study Break',badge:'Student ID',desc:'Medium Margherita with a Coke, made for late-night revision.',inc:'Medium Margherita · Coke',orig:378,price:249,art:['pizza','margherita'],ends:'wk'},
{id:'o11',cat:'bogo',title:'BOGO Margherita',badge:'Buy 1 Get 1',desc:'Two medium Margheritas for the price of one.',inc:'2 × Medium Margherita',orig:658,price:329,art:['pizza','margherita'],ends:'day'},
{id:'o12',cat:'bogo',title:'BOGO Zinger',badge:'Buy 1 Get 1',desc:'Buy one Crispy Chicken Zinger, get the second free.',inc:'2 × Crispy Chicken Zinger',orig:358,price:179,art:['burger','chicken'],ends:'3h'},
{id:'o13',cat:'weekend',title:'Weekend Warrior',badge:'Sat & Sun',desc:'Large Pepperoni, loaded fries, choco lava cake and two Cokes.',inc:'Large Pepperoni · Loaded Fries · Lava Cake · 2 Coke',orig:1055,price:799,art:['combo','pizza'],ends:'we'},
{id:'o14',cat:'weekend',title:'Sunday Funday',badge:'Sat & Sun',desc:'Two Double Smash burgers, wings and a brownie sundae.',inc:'2 Double Smash · Wings (6) · Brownie Sundae',orig:836,price:649,art:['combo','duo'],ends:'we'}];
const OFFER_SECS=[['today',"Today's Deals"],['pizza','Pizza Combos'],['burger','Burger Combos'],['family','Family Packs'],['student','Student Offers'],['bogo','Buy 1 Get 1'],['weekend','Weekend Deals']];
const COUPONS0=[
{code:'WELCOME20',type:'pct',value:20,min:199,max:150,exp:'2027-12-31',active:true,desc:'20% off your order, up to ₹150'},
{code:'FLAT100',type:'flat',value:100,min:599,max:0,exp:'2027-12-31',active:true,desc:'Flat ₹100 off on orders above ₹599'},
{code:'FREESHIP',type:'ship',value:0,min:299,max:0,exp:'2027-12-31',active:true,desc:'Free delivery on orders above ₹299'},
{code:'STUDENT15',type:'pct',value:15,min:149,max:100,exp:'2027-12-31',active:true,desc:'15% off for students, up to ₹100'},
{code:'WEEKEND25',type:'pct',value:25,min:499,max:200,exp:'2027-12-31',active:true,desc:'25% off on weekend orders above ₹499'}];
const BRANCHES=[
{id:'kor',name:'Koramangala',addr:'42, 80 Feet Road, 4th Block, Koramangala, Bengaluru 560034',phone:'+91 80 4001 2201',lat:12.9352,lng:77.6245,hrs:{wd:[660,1410],we:[660,1470]},eta:'25–35'},
{id:'ind',name:'Indiranagar',addr:'118, 100 Feet Road, HAL 2nd Stage, Indiranagar, Bengaluru 560038',phone:'+91 80 4001 2202',lat:12.9784,lng:77.6408,hrs:{wd:[660,1440],we:[660,1500]},eta:'30–40'},
{id:'hsr',name:'HSR Layout',addr:'27th Main Road, Sector 1, HSR Layout, Bengaluru 560102',phone:'+91 80 4001 2203',lat:12.9116,lng:77.6474,hrs:{wd:[630,1380],we:[630,1440]},eta:'30–40'},
{id:'jay',name:'Jayanagar',addr:'9, 11th Main, 4th Block, Jayanagar, Bengaluru 560011',phone:'+91 80 4001 2204',lat:12.9308,lng:77.5838,hrs:{wd:[660,1410],we:[660,1470]},eta:'30–45'}];
const TESTI=[
{n:'Priya Sharma',c:'#B4121B',r:5,t:'The Pepperoni Inferno arrived hot with crisp edges and that hot-honey kick. It has replaced our Friday-night pizza order.',p:'Pepperoni Inferno',a:'Koramangala'},
{n:'Rohan Mehta',c:'#E5620A',r:5,t:'Best zinger burger in Bengaluru, and I have tried them all. Juicy inside, shatter-crisp outside, and never soggy on delivery.',p:'Crispy Chicken Zinger',a:'Indiranagar'},
{n:'Ananya Krishnan',c:'#8E0E15',r:5,t:'Ordering the Couple’s Combo is our date-night ritual. Customising the crust and toppings takes ten seconds in the app.',p:"Couple's Combo",a:'HSR Layout'},
{n:'Vikram Reddy',c:'#1A0F0B',r:4,t:'Loaded fries are dangerous. Ordered a wedge of them alone and finished the box before the movie’s first scene.',p:'Cheesy Loaded Fries',a:'Jayanagar'},
{n:'Sneha Patil',c:'#C7530B',r:5,t:'Finally a veg menu that isn’t an afterthought. The Paneer Tikka Blast pizza is smoky and properly spiced.',p:'Paneer Tikka Blast',a:'Koramangala'},
{n:'Arjun Desai',c:'#B4121B',r:5,t:'Delivered in 28 minutes during rain, still steaming. Live tracking was spot-on and the rider called before arriving.',p:'Solo Feast',a:'Indiranagar'},
{n:'Meera Nair',c:'#8E0E15',r:4,t:'The student deal keeps my hostel budget alive. Aloo Smash, fries and Coke for ₹149 is hard to beat.',p:'Student Meal Deal',a:'HSR Layout'},
{n:'Karthik Bhat',c:'#E5620A',r:5,t:'Family Feast Box fed six of us at my daughter’s birthday. Everything arrived together and packed neatly.',p:'Family Feast Box',a:'Jayanagar'}];
const REV_POOL={pizza:['Crust was crisp outside and chewy inside. The cheese pull was unreal.','Arrived hot with generous toppings. Base did not go soggy even after 25 minutes.','Sauce had a proper tang and the flavours were balanced. Will order again.'],burgers:['Juicy patty, toasted bun and a sauce that actually tastes homemade.','Big, messy and worth it. Portion size is generous for the price.','Stayed crisp through delivery, and the pickles added just the right bite.'],fries:['Crispy on the outside, fluffy inside, and salted just right.','Perfect side for burgers. Portion is huge for the price.','Stayed crunchy for the whole ride home.'],wraps:['Fresh fillings and a flaky wrap that did not tear.','Great value for a filling lunch. The chutney is excellent.','Spice level was spot-on and it was easy to eat at my desk.'],sides:['Golden, crispy and piping hot on arrival.','Great for sharing. The dip is a lovely touch.','Ordered as a starter and it vanished in minutes.'],beverages:['Ice cold and refreshing. Exactly what the meal needed.','Not too sweet and beautifully blended.','Packed securely, no spills at all.'],desserts:['Warm, gooey and gone in three bites.','The perfect end to a heavy meal. Rich but not overpowering.','Looked as good as it tasted.'],combos:['Great value and everything arrived together, hot and fresh.','Saved a good amount versus ordering separately.','Perfect portions for the price. Would happily reorder.']};
const REV_NAMES=['Aditi R.','Sameer K.','Nisha P.','Rahul S.','Divya M.','Kabir A.','Tanvi J.','Harsh V.','Isha G.','Manav T.'];
function seedReviews(){const out={};PRODUCTS0.forEach(p=>{const R=rng(hash(p.id)),n=2+Math.floor(R()*2),pool=REV_POOL[p.cat];out[p.id]=Array.from({length:n},(_,i)=>({id:uid('r'),name:REV_NAMES[Math.floor(R()*REV_NAMES.length)],rating:Math.round(clamp(p.rating+(R()-.6)*1.2,3,5)),text:pool[(i+Math.floor(R()*3))%3],ts:Date.now()-Math.floor(R()*40+1)*DAY,verified:R()>.15,hidden:false,img:''}))});return out}
const POLICIES={terms:['Terms & Conditions',['By placing an order on Ember & Crust you agree to these terms. Prices include applicable taxes unless stated and may change without notice. Offers, coupons and loyalty rewards cannot be combined unless the offer says so, and each carries its own validity and minimum order value.','We reserve the right to decline or cancel any order that cannot be fulfilled, such as when an item is out of stock, the address is outside our delivery radius or we suspect fraudulent activity. When we cancel a prepaid order, the full amount is refunded to the original payment method.','Allergen information is provided in good faith. Our kitchen handles gluten, dairy, nuts, egg and soy, so we cannot guarantee that any item is free from trace allergens.']],
privacy:['Privacy Policy',['We collect the information you give us, such as name, phone number, email, delivery addresses and order history, to prepare and deliver your food, run the loyalty programme and provide support. Payment details are handled by our PCI-compliant payment partner and never stored on our servers.','We never sell your personal data. We share only what is required with delivery partners, payment providers and analytics tools that help us improve the service. You can view, edit or delete your data at any time from your account or by writing to hello@emberandcrust.in.','We send order updates by SMS, email and WhatsApp. Promotional messages are optional and you can unsubscribe with one tap at any time.']],
refund:['Refund Policy',['If your order arrives wrong, incomplete, cold or damaged, tell us within 2 hours of delivery through the support button on the order page. Share a photo where possible and we will remake the item, issue a coupon or refund you in full.','Refunds for prepaid orders are returned to the original payment method within 5–7 business days. Cash-on-delivery refunds are issued as wallet credit or by bank transfer.','Orders cannot be cancelled once the kitchen has started preparing them. Before that point you can cancel from the order page for a full refund.']],
delivery:['Delivery Policy',['We deliver within roughly 6 km of each branch. Delivery costs ₹40 and is free above ₹499, or lower for Silver, Gold and VIP members. Typical delivery time is 25–40 minutes, and we show a live estimate at checkout.','Delivery times may be longer during heavy rain, festivals and peak hours. Pickup orders are ready in approximately 15–20 minutes and held for 30 minutes after they are ready.','Please keep your phone reachable. Our rider will call once if they cannot find your address, and orders left unattended after 10 minutes may be cancelled.']]};
