/* ============ Router + Home ============ */
const PAGES={},AFTER={};let timers=[];
function route(){const h=(location.hash||'#/').replace(/^#/,'');const[p,qs]=h.split('?');const seg=p.split('/').filter(Boolean);return{name:seg[0]||'home',seg:seg.slice(1),q:new URLSearchParams(qs||''),path:p}}
const go=h=>{if(location.hash===h)render();else location.hash=h};
function render(keepScroll){
  timers.forEach(clearInterval);timers=[];const r=route();
  layers.slice().forEach(l=>{if(!$('.panel.pm',l.el)||r.name!=='product')closeLayer(l.el)});
  renderChrome();const app=$('#app');app.className='page';
  const fn=PAGES[r.name]||PAGES.notfound;app.innerHTML=fn(r);void app.offsetWidth;app.classList.add('page-in');
  AFTER[r.name]&&AFTER[r.name](r);if(!keepScroll)window.scrollTo(0,0);tickCd();emit('render')}
function pageHead(t,sub,extra=''){return`<div class="page-head"><div class="wrap"><h1>${t}</h1>${sub?`<p>${sub}</p>`:''}${extra}</div></div>`}
function sectionHead(t,sub,link){return`<div class="sec-h"><div><h2>${t}</h2>${sub?`<p class="muted">${sub}</p>`:''}</div>${link?`<a class="link-arrow" href="${link[0]}">${link[1]} ${ic('arrow')}</a>`:''}</div>`}
const badgeCircle=`<svg viewBox="0 0 120 120" class="spin-badge" aria-hidden="true"><defs><path id="cp" d="M60 60m-44 0a44 44 0 1 1 88 0a44 44 0 1 1-88 0"/></defs><circle cx="60" cy="60" r="58" fill="#FFC53D"/><text font-size="12" font-weight="800" textLength="268" lengthAdjust="spacing" fill="#1A0F0B" font-family="Bricolage Grotesque,sans-serif"><textPath href="#cp">FRESHLY MADE • EVERY DAY •</textPath></text><path d="M60 40c1.5 7 8 10 8 18a8 8 0 0 1-16 0c0-4 2.5-6 4-9 1 3 3 3 4-1z" fill="#B4121B"/></svg>`;
PAGES.home=()=>{
  setMeta('Ember & Crust — Best Pizza & Burger Delivery in Bengaluru','Hot, fresh pizza, burgers and fries delivered in 30 minutes. Order the best pizza and burger near you with easy customisation, live tracking and rewards.');
  const u=me(),oi=openInfo(),best=S.products.filter(p=>p.tag==='best'&&!outOf(p)).slice(0,8);setMenuLD(best);
  const cats=S.cats.map(c=>`<a class="cat-card" href="#/menu/${c.id}"><span class="cat-e" aria-hidden="true">${c.emoji}</span><b>${c.name}</b><small>${S.products.filter(p=>p.cat===c.id).length} items</small></a>`).join('')+`<a class="cat-card star" href="#/menu/best"><span class="cat-e" aria-hidden="true">⭐</span><b>Best Sellers</b><small>Crowd favourites</small></a>`;
  const promos=[['BOGO','Buy 1 Get 1','Two medium Margheritas for the price of one.','#/offers/bogo',['pizza','margherita'],'p-red'],['Combo deals','Meals from ₹149','Burger, fries and Coke bundles that save up to 20%.','#/menu/combos',['combo','solo'],'p-orange'],['Student deals','Campus Combo ₹149','Show your student ID and eat well on a budget.','#/offers/student',['burger','aloo'],'p-gold'],['Family deals','Feast for 4 · ₹1,299','Two large pizzas, sides, wings and four Cokes.','#/offers/family',['combo','family'],'p-ink'],['Weekend offers','Sat & Sun specials','Large Pepperoni, loaded fries and dessert from ₹799.','#/offers/weekend',['combo','pizza'],'p-red',endsAt('we')],['Limited-time offer','Snack Attack ₹249','Loaded fries, nuggets and a Coke while the timer lasts.','#/offers/today',['fries','loaded'],'p-orange',endsAt('3h')]].map(([k,t,d,h,a,c,e])=>`<a class="promo ${c}" href="${h}"><span class="promo-art">${artSVG(a,hash(t),t)}</span><span class="promo-b"><small>${k}</small><b>${t}</b><span>${d}</span>${e?`<span class="promo-cd">Ends in ${cd(e)}</span>`:''}</span></a>`).join('');
  const why=[['leaf','Fresh ingredients','Vegetables cut every morning and dough proved for 48 hours.'],['flame','Made to order','Nothing sits under a heat lamp. We start when you order.'],['truck','Fast delivery','Average delivery in 28 minutes with live rider tracking.'],['shield','Hygienic kitchen','Daily audits, gloved prep and sealed tamper-proof packaging.'],['chef','Best ingredients','Fresh mozzarella, house sauces and free-range chicken.'],['zap','Easy online ordering','Customise in seconds, pay by UPI and reorder in one tap.']].map(([i,t,d])=>`<div class="why"><span class="why-i">${ic(i)}</span><h3>${t}</h3><p>${d}</p></div>`).join('');
  const tcards=TESTI.map(t=>`<figure class="tc">${starRow(t.r)}<blockquote>${esc(t.t)}</blockquote><figcaption>${avatar(t.n,t.c)}<span><b>${t.n}</b><small>Ordered ${t.p} · ${t.a}</small></span></figcaption></figure>`).join('');
  const social=[['p4','4.2k'],['f3','3.1k'],['b2','5.6k'],['p3','2.8k'],['t1','2.2k'],['c3','3.9k']].map(([id,l],i)=>{const p=prod(id);if(!p)return'';const bg=ART_BG[p.art[0]];return`<button class="ig-t" data-act="pv" data-id="${id}" style="--a:${bg[0]};--b:${bg[1]}" aria-label="${esc(p.name)} — view item">${artSVG(p.art,hash(p.id)+i,p.name)}<span class="ig-o"><span>${icFill('heart')} ${l}</span><span>${esc(p.name)}</span></span></button>`}).join('');
  let personal='';
  const last=u&&S.orders.filter(o=>o.uid===u.id&&o.status!=='rejected').sort((a,b)=>b.created-a.created)[0];
  if(u){
    const fc=new Set([...favs(),...S.orders.filter(o=>o.uid===u.id).flatMap(o=>o.items.map(i=>i.pid))].map(id=>prod(id)?.cat).filter(Boolean));
    const owned=new Set(S.orders.filter(o=>o.uid===u.id).flatMap(o=>o.items.map(i=>i.pid)));
    const love=S.products.filter(p=>!outOf(p)&&(favs().includes(p.id)||(fc.has(p.cat)&&!owned.has(p.id)&&p.rating>=4.5))).slice(0,4);
    personal=`<section class="sec"><div class="wrap">${last?`<div class="prev-order"><div><small>Your previous order · ${ago(last.created)}</small><h3>${last.items.map(i=>i.qty+'× '+esc(i.name)).slice(0,3).join(', ')}${last.items.length>3?' +'+(last.items.length-3)+' more':''}</h3><p class="muted">${inr(last.total)} · ${last.type==='pickup'?'Pickup':'Delivery'}</p></div><button class="btn red" data-act="reorder" data-id="${last.id}">${ic('refresh')} Order again</button></div>`:''}
    ${love.length?`${sectionHead('Because you loved it ❤️','Picked from your favourites and past orders.')}<div class="grid">${love.map(card).join('')}</div>`:''}</div></section>`}
  const near=[...S.products].filter(p=>!outOf(p)&&p.cat!=='combos'&&p.cat!=='beverages').sort((a,b)=>b.sold-a.sold).slice(0,4);
  const meal=['s1','f3','d1','t1'].map(prod).filter(Boolean);
  return`<section class="hero"><div class="wrap hero-in"><div class="hero-copy"><span class="hero-tag">${ic('flame')} Freshly Made • Every Day</span><h1>Craving Something <span class="h-ul">Delicious?</span></h1><p class="lead">Hand-stretched pizzas, smashed burgers and fries that stay crisp. Made to order and at your door in about 30 minutes.</p><div class="cta"><a class="btn orange lg" href="#/menu">Order now ${ic('arrow')}</a><a class="btn outline-l lg" href="#/menu">Explore menu</a></div>
  <ul class="hero-facts"><li>${ic('clock')}<span><b>${branch().eta} min</b> delivery</span></li><li>${ic('truck')}<span><b>₹40</b> · free above ₹499</span></li><li>${ic('star')}<span><b>4.8</b> from 10K+ customers</span></li><li><i class="dot ${oi.open?'on':''}"></i><span><b>${oi.short}</b> · ${esc(branch().name)}</span></li></ul></div>
  <div class="hero-art" aria-hidden="true"><div class="plate"><div class="spin">${artSVG(['pizza','pepperoni'],7,'')}</div></div><div class="fl f1">${artSVG(['burger','chicken'],3,'')}</div><div class="fl f2">${artSVG(['fries','loaded'],5,'')}</div><div class="fl f3">${artSVG(['cup','cola'],9,'')}</div>${badgeCircle}<span class="sticker">Fresh<br>Hot<br>Fast</span></div></div></section>
  <div class="marquee" aria-hidden="true"><div><span>Fresh</span><span>Hot</span><span>Delicious</span><span>Fast</span><span>Fresh</span><span>Hot</span><span>Delicious</span><span>Fast</span><span>Fresh</span><span>Hot</span><span>Delicious</span><span>Fast</span></div></div>
  <section class="sec"><div class="wrap">${sectionHead('What are you craving?','Pick a category and start building your order.')}<div class="cats">${cats}</div></div></section>
  ${personal}
  <section class="sec alt"><div class="wrap">${sectionHead('Best sellers','The orders that keep our ovens busy.',['#/menu/best','View all'])}<div class="grid">${best.map(card).join('')}</div></div></section>
  <section class="sec dark"><div class="wrap">${sectionHead('Special offers','Stack the savings. Timers show what’s ending soon.',['#/offers','All offers'])}<div class="promos">${promos}</div></div></section>
  <section class="sec"><div class="wrap">${sectionHead(`Popular near you 🔥`,`Most ordered around ${esc(branch().name)} this week.`)}<div class="grid">${near.map(card).join('')}</div></div></section>
  <section class="sec alt"><div class="wrap">${sectionHead('Complete your meal 🍟','Add a side, a drink or something sweet.')}<div class="meal">${meal.map(miniCard).join('')}</div></div></section>
  <section class="sec"><div class="wrap">${sectionHead('Why choose us','Fast is easy. Fresh is the hard part, and we do both.')}<div class="whys">${why}</div></div></section>
  <section class="sec red"><div class="wrap">${sectionHead('Loved by Bengaluru','Real reviews from verified orders.')}<div class="tcar-w"><div class="tcar" id="tcar" tabindex="0" aria-label="Customer reviews">${tcards}</div><div class="tcar-c"><button class="round-btn" data-act="tcar" data-d="-1" aria-label="Previous review">${ic('left')}</button><button class="round-btn" data-act="tcar" data-d="1" aria-label="Next review">${ic('right')}</button></div></div></div></section>
  <section class="sec"><div class="wrap">${sectionHead('Fresh out of the oven','Follow <b>@emberandcrust</b> on Instagram',[BRAND.social.instagram,'Follow us'])}<div class="ig">${social}</div></div></section>
  <section class="sec news"><div class="wrap"><div class="news-in"><div><h2>Get delicious deals straight to your inbox.</h2><p>New menu drops, weekend offers and members-only coupons. No spam, unsubscribe anytime.</p></div><form data-form="news" class="news-f" novalidate><label class="sr" for="nl">Email address</label><input id="nl" name="email" type="email" placeholder="you@example.com" autocomplete="email" required><button class="btn orange" type="submit">Subscribe</button><span class="err" id="nl-e" role="alert"></span></form></div></div></section>`};
AFTER.home=()=>{const c=$('#tcar');if(!c)return;let paused=false;c.addEventListener('mouseenter',()=>paused=true);c.addEventListener('mouseleave',()=>paused=false);c.addEventListener('focusin',()=>paused=true);c.addEventListener('focusout',()=>paused=false);
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches)timers.push(setInterval(()=>{if(paused||document.hidden)return;const w=c.firstElementChild.offsetWidth+16;if(c.scrollLeft+c.clientWidth>=c.scrollWidth-4)c.scrollTo({left:0,behavior:'smooth'});else c.scrollBy({left:w,behavior:'smooth'})},5500))};
A.tcar=b=>{const c=$('#tcar');c.scrollBy({left:(+b.dataset.d)*(c.firstElementChild.offsetWidth+16),behavior:'smooth'})};
FORMS.news=f=>{const v=f.email.value.trim();if(!V.email(v)){$('#nl-e').textContent='Enter a valid email address, like you@example.com.';f.email.classList.add('bad');f.email.focus();return}
  if(!S.subs.includes(v))S.subs.push(v);save();f.innerHTML=`<div class="ok-anim">${ic('check')}</div><p class="ok-t"><b>You’re in!</b> Check ${esc(v)} for your welcome code.</p>`;toast('Subscribed. Your WELCOME20 code is on the way.','ok')};
A.reorder=b=>{const o=order(b.dataset.id);if(!o)return;let n=0,miss=0;o.items.forEach(i=>{if(i.bundle){S.cart.push({id:uid('l'),bundle:i.bundle,qty:i.qty});n++;return}const p=prod(i.pid);if(!p||outOf(p)){miss++;return}if(addLine(i.pid,{sel:i.sel?JSON.parse(JSON.stringify(i.sel)):null,qty:i.qty,silent:1}))n++});
  if(n){toast(n+' item'+(n>1?'s':'')+' from order #'+o.id+' added'+(miss?` (${miss} unavailable)`:''),'ok');openCart()}else toast('Those items are unavailable right now.','warn')};
