/* ============ About, Contact, Locations, Rewards, Policies ============ */
function proj(lat,lng){return[60+(lng-77.57)*(480/0.11),380-(lat-12.895)*(340/0.1)]}
function mapSVG(active,showYou){
  const pins=BRANCHES.map(b=>{const[x,y]=proj(b.lat,b.lng),on=b.id===active,o=openInfo(b);return`<g class="pin ${on?'on':''}" data-act="pickBranch" data-id="${b.id}" tabindex="0" role="button" aria-label="${b.name} branch, ${o.short}" transform="translate(${x} ${y})"><path d="M0 0C-14-16-20-24-20-34a20 20 0 0 1 40 0C20-24 14-16 0 0z" fill="${on?'#B4121B':'#1A0F0B'}" stroke="#fff" stroke-width="3"/><circle cx="0" cy="-34" r="8" fill="#FFC53D"/><text y="-64" text-anchor="middle" font-size="13" font-weight="700" fill="var(--text)" paint-order="stroke" stroke="var(--surface)" stroke-width="4">${b.name}</text></g>`}).join('');
  const[yx,yy]=proj(userPos.lat,userPos.lng);
  return`<svg class="map" viewBox="0 0 600 420" role="img" aria-label="Map of ${BRAND.name} branches in Bengaluru"><rect width="600" height="420" fill="var(--map)"/><path d="M-10 210C120 170 200 250 320 200S520 120 620 170" stroke="var(--map2)" stroke-width="16" fill="none"/><path d="M60-10C110 90 150 170 140 260S200 380 240 430" stroke="var(--map2)" stroke-width="12" fill="none"/><path d="M420-10C400 80 450 180 420 260S470 370 520 430" stroke="var(--map2)" stroke-width="12" fill="none"/><path d="M-10 320C100 300 240 340 360 310S540 300 620 330" stroke="var(--map2)" stroke-width="9" fill="none"/><path d="M-10 90C120 110 260 60 400 100S560 70 620 60" stroke="var(--map2)" stroke-width="8" fill="none"/><ellipse cx="300" cy="360" rx="70" ry="30" fill="#BFE0D0" opacity=".7"/><path d="M470 250q40-30 80 10t-30 60q-60 20-70-30z" fill="#BCD8EE" opacity=".8"/><path d="M180 60q50-30 90 0t0 50q-60 20-90-50z" fill="#C9E3C0" opacity=".8"/>${showYou?`<g transform="translate(${yx} ${yy})"><circle r="16" fill="#2B7BFF" opacity=".2"/><circle r="7" fill="#2B7BFF" stroke="#fff" stroke-width="3"/><text y="28" text-anchor="middle" font-size="12" font-weight="700" fill="var(--text)">You</text></g>`:''}${pins}</svg>`}
const hoursTable=b=>{const t=new Date().getDay();return`<table class="hrs"><tbody>${[1,2,3,4,5,6,0].map(d=>`<tr class="${d===t?'today':''}"><th scope="row">${DAYS[d]}</th><td>${hrsText(b,d)}</td></tr>`).join('')}</tbody></table>`};
PAGES.about=()=>{
  setMeta('About Ember & Crust — Our Story, Chefs & Fresh Ingredients','Meet the team behind Bengaluru’s favourite pizza and burger kitchen. Fresh dough, real cheese and a customer-first promise.');
  const scene=(t,inner,bg)=>`<figure class="scene" style="--b:${bg}"><svg viewBox="0 0 240 170" role="img" aria-label="${t}">${inner}</svg><figcaption>${t}</figcaption></figure>`;
  const oven='<rect width="240" height="170" fill="#F6D9B8"/><rect x="40" y="70" width="160" height="100" rx="8" fill="#B4501F"/><path d="M70 170V110a50 50 0 0 1 100 0v60z" fill="#2A1510"/><path d="M120 165c-16-8-20-24-8-38 2 8 8 10 10 4 6 8 18 14 10 30-3 6-8 6-12 4z" fill="#FF7A1A"/><path d="M120 165c-8-4-9-12-2-19 2 5 5 5 6 2 4 6 8 10 3 16z" fill="#FFC53D"/><path d="M40 70l80-50 80 50z" fill="#8E0E15"/><rect x="108" y="10" width="24" height="20" fill="#5A2A18"/>';
  const dough='<rect width="240" height="170" fill="#FFF0D6"/><ellipse cx="120" cy="120" rx="90" ry="26" fill="#E7B87B"/><ellipse cx="120" cy="112" rx="70" ry="30" fill="#FFF6E2"/><rect x="40" y="60" width="160" height="16" rx="8" fill="#C98B4D" transform="rotate(-12 120 68)"/><circle cx="52" cy="70" r="9" fill="#A9691F" transform="rotate(-12 120 68)"/><circle cx="188" cy="66" r="9" fill="#A9691F" transform="rotate(-12 120 68)"/><g fill="#fff" opacity=".9"><circle cx="90" cy="130" r="3"/><circle cx="130" cy="138" r="2"/><circle cx="160" cy="126" r="3"/></g>';
  const veg='<rect width="240" height="170" fill="#E8F0D2"/><circle cx="70" cy="100" r="38" fill="#D63A25"/><path d="M60 64c6-10 18-10 24 0-8-2-16-2-24 0z" fill="#2F8F3A"/><ellipse cx="150" cy="110" rx="34" ry="26" fill="#EBD9C0"/><ellipse cx="150" cy="96" rx="30" ry="14" fill="#B79B84"/><path d="M180 50q30 20 20 60-30-10-20-60z" fill="#3E9B3A"/><path d="M196 60l-8 40" stroke="#2A7B2E" stroke-width="2"/>';
  const team=[['Chef Rohit Nair','Head Chef','Trained in Naples. Obsessed with 48-hour dough and the perfect leopard-spotted crust.','#B4121B'],['Chef Meghna Rao','Burger Lead','Runs our smash-burger station and the sauce lab. Every patty is seared to order.','#E5620A'],['Imran Qureshi','Kitchen Manager','Keeps every order moving, from first ticket to last handover.','#1A0F0B'],['Deepa Krishnan','Customer Happiness','Reads every review and makes sure no order goes wrong twice.','#8E0E15']];
  return`<section class="about-hero"><div class="wrap"><h1>Two friends, one wood-fired oven, and a very stubborn idea.</h1><p>We started Ember &amp; Crust in 2019 with a single oven in Koramangala. The plan was simple: pizza and burgers that taste like they should, delivered while they’re still hot.</p></div></section>
  <section class="sec"><div class="wrap"><div class="stats">${[['10K+','Happy customers'],['50K+','Orders delivered'],['4.8★','Average rating'],['4','Bengaluru branches']].map(([n,l])=>`<div class="stat"><b data-count="${n}">${n}</b><span>${l}</span></div>`).join('')}</div></div></section>
  <section class="sec alt"><div class="wrap two"><div><h2>Our story</h2><p>Aditya and Karan were flatmates who couldn’t find a pizza that arrived crisp. So they built one: dough fermented for two days, sauce simmered from ripe tomatoes and mozzarella that actually stretches.</p><p>Burgers came next, smashed hard on a screaming-hot griddle. Then fries that stay crunchy for the whole ride home. Today we cook for thousands of neighbours a week, with the same rule we started with: <b>if we wouldn’t eat it, we don’t send it.</b></p></div><div class="scenes">${scene('Wood-fired oven',oven)}${scene('Dough proved 48 hours',dough)}${scene('Vegetables cut each morning',veg)}</div></div></section>
  <section class="sec"><div class="wrap">${sectionHead('What we stand for')}<div class="whys">${[['flame','Our mission','Make fresh, honest comfort food and get it to your door hot, fast and fairly priced.'],['chef','Food philosophy','Few ingredients, done properly. We make our sauces, proof our dough and never pre-cook.'],['leaf','Quality ingredients','Fresh mozzarella, free-range chicken, farm vegetables and no artificial colours.'],['users','Customer first','Wrong order? Cold pizza? Tell us and we’ll fix it with a remake or full refund.']].map(([i,t,d])=>`<div class="why"><span class="why-i">${ic(i)}</span><h3>${t}</h3><p>${d}</p></div>`).join('')}</div></div></section>
  <section class="sec alt"><div class="wrap">${sectionHead('Meet the kitchen crew')}<div class="team">${team.map(([n,r,d,c])=>`<article class="tm">${avatar(n.replace('Chef ',''),c)}<h3>${n}</h3><small>${r}</small><p>${d}</p></article>`).join('')}</div></div></section>
  <section class="sec"><div class="wrap cta-band"><h2>Hungry yet?</h2><p>See what the fuss is about. Your first order gets 20% off.</p><a class="btn orange lg" href="#/menu">Order now ${ic('arrow')}</a></div></section>`};
AFTER.about=()=>{const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;io.unobserve(e.target);const t=e.target.dataset.count,m=t.match(/^([\d.]+)(.*)$/);if(!m||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const end=+m[1],st=performance.now();(function f(n){const k=Math.min(1,(n-st)/1100);e.target.textContent=(Number.isInteger(end)?Math.round(end*k):(end*k).toFixed(1))+m[2];if(k<1)requestAnimationFrame(f)})(st)}),{threshold:.6});$$('[data-count]').forEach(e=>io.observe(e))};
PAGES.contact=()=>{
  setMeta('Contact & Opening Hours | Ember & Crust Pizza & Burgers','Find our address, phone number and opening hours. Message us or chat on WhatsApp for orders, catering and feedback.');
  const b=branch(),oi=openInfo(b),soc=[['ig','instagram','Instagram'],['fb','facebook','Facebook'],['xx','x','X'],['yt','youtube','YouTube']].map(([i,k,l])=>`<a class="soc" href="${BRAND.social[k]}" target="_blank" rel="noopener" aria-label="${l}">${ic(i)}</a>`).join('');
  return`${pageHead('Get in touch','We reply within a few minutes during opening hours.')}<div class="wrap contact"><div class="c-info"><div class="c-card"><div class="row between"><h2>${b.name} branch</h2><span class="status ${oi.open?'open':'closed'}"><i class="dot ${oi.open?'on':''}"></i>${oi.open?'Open now':'Closed'}</span></div><p class="muted">${oi.text}</p><ul class="c-list"><li>${ic('pin')}<span>${esc(b.addr)}</span></li><li>${ic('phone')}<a href="tel:${b.phone.replace(/\s/g,'')}">${b.phone}</a></li><li>${ic('mail')}<a href="mailto:${BRAND.email}">${BRAND.email}</a></li></ul><h3>Opening hours</h3>${hoursTable(b)}<div class="row wrap-r"><a class="btn wa" href="https://wa.me/${BRAND.wa}?text=${encodeURIComponent('Hi Ember & Crust!')}" target="_blank" rel="noopener">${ic('wa')} Chat on WhatsApp</a><button class="btn ghost" data-act="branch">Change branch</button></div><div class="socs dark">${soc}</div></div></div>
  <div class="c-side"><div class="map-w">${mapSVG(b.id,false)}<a class="btn ink sm map-dir" href="https://www.google.com/maps/dir/?api=1&destination=${b.lat},${b.lng}" target="_blank" rel="noopener">${ic('ext')} Get directions</a></div>
  <form class="c-card form" data-form="contact" novalidate><h2>Send us a message</h2><div class="g2">${field({id:'cn',label:'Your name',req:1,ac:'name',value:me()?.name||''})}${field({id:'cp',label:'Mobile number',type:'tel',req:1,ac:'tel',mode:'numeric',value:me()?.phone||''})}</div>${field({id:'ce',label:'Email',type:'email',req:1,ac:'email',value:me()?.email||''})}<div class="fld"><label for="cm">Message <span class="req" aria-hidden="true">*</span></label><textarea id="cm" name="cm" rows="4" required placeholder="Order feedback, party bookings, franchise enquiries…"></textarea><span class="err" id="cm-e" role="alert"></span></div><button class="btn red lg" type="submit">Send message</button></form></div></div>`};
FORMS.contact=f=>{if(!checkForm(f,[['cn',v=>v.length>1,'Enter your name.'],['cp',V.phone,'Enter a valid 10-digit mobile number.'],['ce',V.email,'Enter a valid email address.'],['cm',v=>v.length>=8,'Write a short message (at least 8 characters).']]))return;
  S.msgs.unshift({id:uid('m'),name:f.cn.value,phone:f.cp.value,email:f.ce.value,text:f.cm.value,ts:Date.now()});save();f.cm.value='';toast('Message sent. We’ll get back to you shortly.','ok')};
FORMS.support=f=>{const m=f.m.value.trim();if(m.length<5){$('#sm-e').textContent='Please describe the problem in a few words.';return}S.msgs.unshift({id:uid('m'),name:me()?.name||'Guest',phone:me()?.phone||'',email:me()?.email||'',text:(f.dataset.oid?'[Order '+f.dataset.oid+'] ':'')+m,ts:Date.now()});save();closeLayer(f.closest('.layer'));toast('Support request sent. Expect a reply within minutes.','ok')};
/* Locations */
let LQ='';
PAGES.locations=()=>{
  setMeta('Restaurant Locations — Pizza & Burger Near You | Ember & Crust','Find the nearest Ember & Crust branch in Bengaluru. See distance, opening hours, phone numbers and order from your closest kitchen.');
  return`${pageHead('Find your nearest branch','Four kitchens across Bengaluru. Pick one and order from it.')}<div class="wrap loc"><div class="loc-l"><form class="search" role="search" data-form="noop"><span class="s-ic">${ic('search')}</span><label class="sr" for="lsearch">Search by area or pincode</label><input id="lsearch" type="search" placeholder="Search area or pincode (e.g. HSR, 560034)" value="${esc(LQ)}"><button type="button" class="btn ghost sm" data-act="locate" aria-label="Use my location">${ic('pin')}<span class="btn-t"> Use my location</span></button></form><ul class="br-cards" id="br-cards">${branchCards()}</ul></div><div class="loc-r"><div class="map-w sticky-m" id="loc-map">${mapSVG(S.branch,true)}</div></div></div>`};
function branchCards(){const q=LQ.toLowerCase();const l=BRANCHES.filter(b=>!q||(b.name+' '+b.addr).toLowerCase().includes(q)).map(b=>({b,d:dist(userPos,b)})).sort((a,c)=>a.d-c.d);
  return l.length?l.map(({b,d})=>{const o=openInfo(b);return`<li class="br-card ${b.id===S.branch?'on':''}"><div class="row between"><h3>${b.name}</h3><span class="status ${o.open?'open':'closed'}"><i class="dot ${o.open?'on':''}"></i>${o.short}</span></div><p class="muted">${esc(b.addr)}</p><p class="br-m">${ic('pin')} ${d.toFixed(1)} km ${userPos.real?'from you':'from MG Road'} · ${ic('clock')} ${b.eta} min · ${o.text.replace('Open now · ','').replace('Closed · ','')}</p><div class="row wrap-r"><a class="btn ghost sm" href="tel:${b.phone.replace(/\s/g,'')}">${ic('phone')} ${b.phone}</a><button class="btn red sm" data-act="orderFrom" data-id="${b.id}">Order from this location</button></div></li>`}).join(''):`<li>${emptyState('pin','No branch matches','Try an area like “HSR” or “Indiranagar”.')}</li>`}
document.addEventListener('input',e=>{if(e.target.id==='lsearch'){LQ=e.target.value;$('#br-cards').innerHTML=branchCards()}});
A.pickBranch=b=>{S.branch=b.dataset.id;save();renderChrome();if(route().name==='locations'){$('#br-cards').innerHTML=branchCards();$('#loc-map').innerHTML=mapSVG(S.branch,true)}else if(route().name==='contact')render(true);toast(branch().name+' selected','ok')};
A.orderFrom=b=>{S.branch=b.dataset.id;save();toast('Ordering from '+branch().name,'ok');go('#/menu')};
A.locate=()=>{if(!navigator.geolocation){toast('Location isn’t available on this device.','warn');return}navigator.geolocation.getCurrentPosition(p=>{userPos={lat:p.coords.latitude,lng:p.coords.longitude,real:true};$('#br-cards').innerHTML=branchCards();$('#loc-map').innerHTML=mapSVG(S.branch,true);toast('Showing distances from your location','ok')},()=>toast('We couldn’t get your location. Showing distances from MG Road.','warn'),{timeout:6000})};
A.setBranch=b=>{S.branch=b.dataset.id;save();closeLayer(b.closest('.layer'));render(true);toast('Branch set to '+branch().name,'ok')};
A.branch=()=>openBranch();
/* Rewards */
const REWARDS=[{id:'rw1',name:'Free Classic Fries',cost:100,pid:'f1',ic:'🍟'},{id:'rw2',name:'Free Garlic Bread',cost:150,pid:'s1',ic:'🥖'},{id:'rw3',name:'Free Choco Lava Cake',cost:200,pid:'t1',ic:'🍫'},{id:'rw4',name:'₹100 off coupon',cost:300,coupon:100,ic:'🎟️'},{id:'rw5',name:'Free Medium Margherita',cost:600,pid:'p1',sel:{size:'M',crust:'reg',xc:0,tops:[],sauces:[]},ic:'🍕'}];
PAGES.rewards=()=>{
  setMeta('Rewards & Loyalty Program | Ember & Crust','Earn 1 point for every ₹10 you spend. Climb from Regular to Silver, Gold and VIP and unlock free food, bonus points and free delivery.');
  const u=me(),t=u?tierOf(u.life):TIERS[0],ni=TIERS[tierIdx(u?u.life:0)+1],pct=ni?clamp(((u?u.life:0)-t.min)/(ni.min-t.min)*100,0,100):100;
  const hero=u?`<div class="loy-card" style="--tc:${t.c}"><div class="loy-top"><div><small>${esc(u.name)}</small><b class="loy-pts">${u.pts.toLocaleString('en-IN')}</b><span>points available</span></div><span class="tier-b">${ic('crown')} ${t.n}</span></div><div class="bar lg"><i style="width:${pct}%"></i></div><p>${ni?`<b>${(ni.min-u.life).toLocaleString('en-IN')}</b> more points to reach <b>${ni.n}</b>`:'You’re at our top level. Thank you!'}</p></div>`:`<div class="loy-card guest"><h2>Join to start earning</h2><p>Sign up free and get 1 point for every ₹10 you spend, plus a welcome coupon.</p><button class="btn orange lg" data-act="login">Log in or sign up</button></div>`;
  return`${pageHead('Rewards','Earn 1 point for every ₹10 you spend. Redeem for free food and coupons.')}<div class="wrap loy">${hero}
  <section><h2>Redeem your points</h2><div class="rw-grid">${REWARDS.map(r=>`<article class="rw ${u&&u.pts>=r.cost?'':'lock'}"><span class="rw-e" aria-hidden="true">${r.ic}</span><h3>${r.name}</h3><b>${r.cost} pts</b><button class="btn ${u&&u.pts>=r.cost?'orange':'ghost'} sm" data-act="redeem" data-id="${r.id}" ${u&&u.pts<r.cost?'disabled':''}>${u?(u.pts>=r.cost?'Redeem':'Need '+(r.cost-u.pts)+' more'):'Log in to redeem'}</button></article>`).join('')}</div></section>
  <section><h2>Membership levels</h2><div class="tiers">${[['Regular','Start earning from your first order.','1 pt per ₹10','Free delivery above ₹499'],['Silver','500 lifetime points','+5% bonus points','Free delivery above ₹449'],['Gold','1,500 lifetime points','+10% bonus points','Free delivery above ₹349'],['VIP','3,000 lifetime points','+20% bonus points','Free delivery on every order']].map(([n,a,b,c],i)=>`<article class="tier ${u&&tierOf(u.life).n===n?'cur':''}" style="--tc:${TIERS[i].c}"><h3>${ic('crown')} ${n}</h3><p class="muted">${a}</p><ul><li>${ic('check')} ${b}</li><li>${ic('check')} ${c}</li></ul></article>`).join('')}</div></section>
  <section class="how"><h2>How it works</h2><ol><li><b>Order</b> from the app or website and pay any way you like.</li><li><b>Earn</b> 1 point per ₹10 spent once your order is delivered.</li><li><b>Redeem</b> points for free food or coupons and enjoy.</li></ol></section></div>`};
A.redeem=b=>{const u=me();if(!u){openAuth('login');return}const r=REWARDS.find(x=>x.id===b.dataset.id);if(u.pts<r.cost){toast('You need '+(r.cost-u.pts)+' more points.','warn');return}
  u.pts-=r.cost;if(r.coupon){const code='RWD'+uid().slice(0,4).toUpperCase();S.coupons.push({code,type:'flat',value:r.coupon,min:299,max:0,exp:new Date(Date.now()+30*DAY).toISOString().slice(0,10),active:true,desc:'Reward coupon: flat ₹'+r.coupon+' off',reward:1});S.coupon=code;toast('Coupon '+code+' saved and applied to your cart','ok',{label:'View cart',act:'cart'})}
  else{const p=prod(r.pid);const ok=addLine(r.pid,{sel:r.sel||defSel(p),silent:1,reward:r.cost});if(!ok){u.pts+=r.cost;return}toast(r.name+' added to your cart','ok',{label:'View cart',act:'cart'})}save();render(true)};
PAGES.policy=r=>{const p=POLICIES[r.seg[0]];if(!p)return PAGES.notfound();setMeta(p[0]+' | Ember & Crust',p[1][0].slice(0,150));return`${pageHead(p[0],'Last updated 1 September 2026')}<div class="wrap prose">${p[1].map(x=>`<p>${x}</p>`).join('')}<p class="muted">Questions? Email <a href="mailto:${BRAND.email}">${BRAND.email}</a>.</p></div>`};
PAGES.notfound=()=>{setMeta('Page not found | Ember & Crust','');return`<div class="wrap">${emptyState('search','We couldn’t find that page','It may have moved, or the link is mistyped.','<a class="btn red" href="#/">Back to home</a>')}</div>`};
