/* ============ Admin dashboard & Kitchen display ============ */
const ADM_NAV=[['overview','Overview','gauge'],['orders','Orders','receipt'],['products','Products','box'],['offers','Offers','tag'],['customers','Customers','users'],['reviews','Reviews','star'],['analytics','Analytics','chart']];
IC.gauge='<path d="m12 14 4-4"/><path d="M3.34 19a10 10 0 1 1 17.32 0"/>';
const ACTIVE=['new','confirmed','preparing','ready','out'];
const todayOrders=()=>S.orders.filter(o=>o.created>=dayStart());
const sales=l=>l.filter(o=>o.status!=='rejected').reduce((a,o)=>a+o.total,0);
/* ----- charts ----- */
function niceMax(v){if(v<=0)return 1;const p=Math.pow(10,Math.floor(Math.log10(v))),n=v/p;return(n<=1?1:n<=2?2:n<=5?5:10)*p}
const short=n=>n>=1e5?(n/1e5).toFixed(1).replace(/\.0$/,'')+'L':n>=1e3?(n/1e3).toFixed(n>=1e4?0:1).replace(/\.0$/,'')+'k':String(Math.round(n));
function axes(max,W,H,l,t,b){let s='';for(let i=0;i<=4;i++){const y=t+(H-t-b)*(1-i/4);s+=`<line x1="${l}" x2="${W-8}" y1="${y}" y2="${y}" stroke="var(--line)"/><text x="${l-6}" y="${y+4}" text-anchor="end" font-size="11" fill="var(--muted)">${short(max*i/4)}</text>`}return s}
function barChart(vals,labels,color='#FF7A1A',fmt=inr){const W=640,H=250,l=46,t=12,b=32,max=niceMax(Math.max(...vals)),bw=(W-l-8)/vals.length;
  return`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Bar chart">${axes(max,W,H,l,t,b)}${vals.map((v,i)=>{const h=(H-t-b)*v/max;return`<g><rect x="${l+i*bw+bw*.16}" y="${H-b-h}" width="${bw*.68}" height="${h}" rx="4" fill="${i===vals.length-1?'#B4121B':color}"><title>${labels[i]}: ${fmt(v)}</title></rect>${i%Math.ceil(vals.length/8)===0||i===vals.length-1&&vals.length<=8?`<text x="${l+i*bw+bw/2}" y="${H-10}" text-anchor="middle" font-size="10.5" fill="var(--muted)">${labels[i]}</text>`:''}</g>`}).join('')}</svg>`}
function lineChart(series,labels,fmt=inr){const W=640,H=250,l=46,t=12,b=32,max=niceMax(Math.max(...series.flatMap(s=>s.vals))),n=labels.length,x=i=>l+(W-l-14)*i/(n-1),y=v=>H-b-(H-t-b)*v/max;
  return`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Line chart">${axes(max,W,H,l,t,b)}${series.map(s=>{const p=s.vals.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1)).join('');return`${s.area?`<path d="${p}L${x(n-1)} ${H-b}L${x(0)} ${H-b}z" fill="${s.color}" opacity=".14"/>`:''}<path d="${p}" fill="none" stroke="${s.color}" stroke-width="${s.thin?1.6:2.6}" ${s.dash?'stroke-dasharray="5 4"':''} stroke-linejoin="round" stroke-linecap="round"/>`+(s.dots?s.vals.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="3.4" fill="${s.color}"><title>${labels[i]}: ${fmt(v)}</title></circle>`).join(''):'')}).join('')}${labels.map((lb,i)=>i%Math.ceil(n/8)===0?`<text x="${x(i)}" y="${H-10}" text-anchor="middle" font-size="10.5" fill="var(--muted)">${lb}</text>`:'').join('')}</svg>`}
function hbar(items){const max=Math.max(...items.map(i=>i[1]));return`<ul class="hbar">${items.map(([n,v],i)=>`<li><span>${esc(n)}</span><div class="bar"><i style="width:${v/max*100}%;background:${i?'#FF7A1A':'#B4121B'}"></i></div><b>${v.toLocaleString('en-IN')}</b></li>`).join('')}</ul>`}
function donut(items){const tot=items.reduce((a,i)=>a+i[1],0),C=['#B4121B','#FF7A1A','#FFC53D','#1A0F0B','#1E9E4A','#8E6A5A','#E5620A','#C2A896'];let a=-Math.PI/2;const R=70,r=44;
  const arcs=items.map(([n,v],i)=>{const f=v/tot,a2=a+f*2*Math.PI,P=(ang,rad)=>[100+Math.cos(ang)*rad,100+Math.sin(ang)*rad],[x1,y1]=P(a,R),[x2,y2]=P(a2,R),[x3,y3]=P(a2,r),[x4,y4]=P(a,r),lg=f>.5?1:0;const d=`M${x1} ${y1}A${R} ${R} 0 ${lg} 1 ${x2} ${y2}L${x3} ${y3}A${r} ${r} 0 ${lg} 0 ${x4} ${y4}z`;a=a2;return`<path d="${d}" fill="${C[i%8]}"><title>${n}: ${Math.round(f*100)}%</title></path>`}).join('');
  return`<div class="donut"><svg viewBox="0 0 200 200" role="img" aria-label="Category share">${arcs}<text x="100" y="98" text-anchor="middle" font-size="20" font-weight="800" fill="var(--text)">${items.length}</text><text x="100" y="116" text-anchor="middle" font-size="11" fill="var(--muted)">categories</text></svg><ul>${items.map(([n,v],i)=>`<li><i style="background:${C[i%8]}"></i>${esc(n)} <b>${Math.round(v/tot*100)}%</b></li>`).join('')}</ul></div>`}
/* ----- shell ----- */
let AN={range:'daily'},OF='all',PS='';
PAGES.admin=r=>{setMeta('Admin dashboard | Ember & Crust','');
  if(!S.adminAuth)return`<div class="adm-login"><form class="co-card form" data-form="adminLogin" novalidate><a class="logo" href="#/">${LOGO}<span><b>Ember <i>&amp;</i> Crust</b><small>Owner dashboard</small></span></a><h1>Sign in</h1>${field({id:'aem',label:'Email',type:'email',req:1,value:BRAND.adminEmail,ac:'username'})}${field({id:'apw',label:'Password',type:'password',req:1,ac:'current-password'})}<button class="btn red block lg" type="submit">Sign in</button><p class="muted small center">Demo credentials: ${BRAND.adminEmail} / ${BRAND.adminPass}<br>In production, sign in with Supabase Auth and role-based access.</p><a class="txt-btn center" href="#/">← Back to website</a></form></div>`;
  const sec=r.seg[0]||'overview',pend=S.orders.filter(o=>['new'].includes(o.status)).length;
  const fn=ADM[sec]||ADM.overview;
  return`<div class="adm"><aside class="adm-side"><a class="logo" href="#/">${LOGO}<span><b>Ember <i>&amp;</i> Crust</b><small>Owner dashboard</small></span></a><nav aria-label="Admin">${ADM_NAV.map(([k,l,i])=>`<a href="#/admin/${k}" ${sec===k?'aria-current="page"':''}>${ic(i)}<span>${l}</span>${k==='orders'&&pend?`<i class="cnt">${pend}</i>`:''}</a>`).join('')}<a href="#/kitchen">${ic('cook')}<span>Kitchen display</span></a></nav><div class="adm-f"><a href="#/">${ic('ext')} View website</a><button data-act="adminOut">${ic('logout')} Sign out</button></div></aside>
  <div class="adm-main"><header class="adm-top"><h1>${(ADM_NAV.find(x=>x[0]===sec)||ADM_NAV[0])[1]}</h1><div class="row"><label class="tgl sm"><input type="checkbox" id="autoT" ${S.auto?'checked':''}><span class="tgl-t">Demo auto-progress</span></label><button class="btn orange sm" data-act="simOrder">${ic('plus')} Simulate order</button></div></header><div class="adm-body" id="adm-body">${fn()}</div></div></div>`};
FORMS.adminLogin=f=>{if(!checkForm(f,[['aem',V.email,'Enter your admin email.'],['apw',v=>v.length>0,'Enter your password.']]))return;if(f.aem.value.trim().toLowerCase()!==BRAND.adminEmail||f.apw.value!==BRAND.adminPass){$('#apw-e').textContent='Incorrect email or password.';return}S.adminAuth=true;save();render();toast('Signed in','ok')};
A.adminOut=()=>{S.adminAuth=false;save();go('#/admin')};
document.addEventListener('change',e=>{if(e.target.id==='autoT'){S.auto=e.target.checked;save();toast('Demo auto-progress '+(S.auto?'on':'off'),'ok')}});
const kpi=(l,v,s,i)=>`<div class="kpi"><span class="kpi-i">${ic(i)}</span><small>${l}</small><b>${v}</b>${s?`<em>${s}</em>`:''}</div>`;
const ADM={};
const dl=i=>new Date(i).toLocaleDateString('en-IN',{day:'numeric',month:'short'});
ADM.overview=()=>{const td=todayOrders(),h=salesHist(),last=h.slice(-14),pend=td.filter(o=>['new','confirmed','preparing'].includes(o.status)).length,done=td.filter(o=>o.status==='delivered').length,aov=td.filter(o=>o.status!=='rejected').length?sales(td)/td.filter(o=>o.status!=='rejected').length:0;
  const top=[...S.products].sort((a,b)=>b.sold-a.sold).slice(0,6).map(p=>[p.name,p.sold]);
  return`<div class="kpis">${kpi("Today's sales",inr(sales(td)),'since midnight','wallet')}${kpi('Total orders',td.length,'today','receipt')}${kpi('Pending orders',pend,'need attention','clock')}${kpi('Completed',done,'delivered today','check')}${kpi('Customers',(10284+S.users.length-1).toLocaleString('en-IN'),'all time','users')}${kpi('Avg. order value',inr(aov),'today','chart')}</div>
  <div class="adm-grid"><section class="co-card"><h2>Daily sales · last 14 days</h2>${barChart(last.map(d=>d.sales),last.map(d=>dl(d.ts)))}</section><section class="co-card"><h2>Best sellers</h2>${hbar(top)}</section></div>
  <section class="co-card"><div class="row between"><h2>Live orders</h2><a class="link-arrow" href="#/admin/orders">Manage all ${ic('arrow')}</a></div>${ordersTable(S.orders.slice(0,7))}</section>`};
/* ----- orders ----- */
const FILT={all:o=>1,new:o=>o.status==='new',kitchen:o=>['confirmed','preparing','ready'].includes(o.status),out:o=>o.status==='out',done:o=>o.status==='delivered',rej:o=>o.status==='rejected'};
function ordersTable(l){if(!l.length)return emptyState('receipt','No orders here','New orders will appear as soon as customers place them.');
  return`<div class="tbl-w"><table class="tbl"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>Placed</th><th><span class="sr">Actions</span></th></tr></thead><tbody>${l.map(o=>`<tr><td><b>#${o.id}</b><small>${o.type==='pickup'?'Pickup':'Delivery'} · ${o.pay}</small></td><td>${esc(o.cust.name)}<small>${esc(o.cust.phone)}</small></td><td class="items-c">${o.items.map(i=>i.qty+'× '+esc(i.name)).slice(0,2).join(', ')}${o.items.length>2?' +'+(o.items.length-2):''}</td><td><b>${inr(o.total)}</b></td><td>${o.status==='new'?`<span class="pill st-new">New</span>`:o.status==='rejected'?`<span class="pill st-rejected">Rejected</span>`:`<label class="sel sm"><span class="sr">Status for ${o.id}</span><select data-ost="${o.id}">${flow(o).slice(1).map(s=>`<option value="${s}" ${o.status===s?'selected':''}>${STATUS_LABEL[s]}${s==='ready'&&o.type==='pickup'?' for pickup':''}</option>`).join('')}</select></label>`}</td><td>${ago(o.created)}</td><td class="act-c">${o.status==='new'?`<button class="btn orange sm" data-act="oAccept" data-id="${o.id}">Accept</button><button class="btn ghost sm danger" data-act="oReject" data-id="${o.id}">Reject</button>`:''}<button class="btn ghost sm" data-act="oView" data-id="${o.id}">View</button></td></tr>`).join('')}</tbody></table></div>`}
ADM.orders=()=>{const tabs=[['all','All'],['new','New'],['kitchen','In kitchen'],['out','Out for delivery'],['done','Completed'],['rej','Rejected']];const l=S.orders.filter(FILT[OF]);
  return`<div class="chips" role="tablist">${tabs.map(([k,n])=>`<button class="chip ${OF===k?'on':''}" role="tab" aria-selected="${OF===k}" data-act="oFilter" data-f="${k}">${n} <b>${S.orders.filter(FILT[k]).length}</b></button>`).join('')}</div><section class="co-card">${ordersTable(l.slice(0,60))}</section>`};
A.oFilter=b=>{OF=b.dataset.f;$('#adm-body').innerHTML=ADM.orders()};
A.oAccept=b=>{const o=order(b.dataset.id);o.auto=false;setStatus(o,'confirmed');toast('Order #'+o.id+' accepted','ok')};
A.oReject=b=>confirmBox('Reject order #'+b.dataset.id+'?','The customer will be notified and refunded.','Reject order',()=>{const o=order(b.dataset.id);o.auto=false;setStatus(o,'rejected')});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.ost){const o=order(t.dataset.ost);o.auto=false;setStatus(o,t.value);toast('#'+o.id+' → '+STATUS_LABEL[t.value],'ok')}});
A.oView=b=>{const o=order(b.dataset.id);openLayer(`<div class="dr-h"><h2>Order #${o.id}</h2><button class="x-btn" data-act="closeLayer" aria-label="Close">${ic('x')}</button></div><div class="pad"><span class="pill st-${o.status}">${STATUS_LABEL[o.status]}</span><h3>Customer</h3><p><b>${esc(o.cust.name)}</b><br>${esc(o.cust.phone)} · ${esc(o.cust.email)}</p><h3>${o.type==='pickup'?'Pickup':'Delivery address'}</h3><p>${o.type==='pickup'?esc(branch(o.branch).name)+' branch':esc(fmtAddr(o.addr))}</p><h3>Items</h3><ul class="os-l">${o.items.map(i=>`<li><span></span><span><b>${i.qty} × ${esc(i.name)}</b>${i.summary?`<small>${esc(i.summary)}</small>`:''}${i.instr?`<small>“${esc(i.instr)}”</small>`:''}</span><b>${inr(i.unit*i.qty)}</b></li>`).join('')}</ul>${o.note?`<p class="note-i"><b>Instructions:</b> ${esc(o.note)}</p>`:''}<dl class="sum"><div><dt>Subtotal</dt><dd>${inr(o.sub)}</dd></div>${o.disc?`<div class="g"><dt>Discount</dt><dd>−${inr(o.disc)}</dd></div>`:''}<div><dt>Fees & taxes</dt><dd>${inr(o.fee+o.tax)}</dd></div><div class="tot"><dt>Total · ${o.pay}</dt><dd>${inr(o.total)}</dd></div></dl></div>`,{kind:'sheet',cls:'sm',label:'Order details'})};
A.simOrder=()=>{const R=Math.random,c=SEED_CUST[Math.floor(R()*SEED_CUST.length)],pool=S.products.filter(p=>!outOf(p)),items=Array.from({length:1+Math.floor(R()*3)},()=>{const p=pool[Math.floor(R()*pool.length)],sel=defSel(p);return{pid:p.id,name:p.name,qty:1+Math.floor(R()*2),unit:p.price+selPrice(p,sel),sel,summary:selSummary(p,sel),art:p.art,instr:''}});
  const sub=items.reduce((a,i)=>a+i.unit*i.qty,0),type=R()>.25?'delivery':'pickup',fee=type==='pickup'||sub>=499?0:40,tax=Math.round(sub*.05),b=BRANCHES[Math.floor(R()*4)];
  const o={id:'EC-'+(S.seq++),uid:'c_sim',cust:{name:c[0],phone:c[1].replace('xxxx','0'+Math.floor(R()*90+10)),email:slug(c[0]).replace('-','.')+'@example.com'},items,sub,disc:0,fee,tax,total:sub+fee+tax,coupon:'',type,addr:type==='delivery'?{house:'Flat '+Math.floor(R()*400+1),street:'Main Road',area:b.name,city:'Bengaluru',state:'Karnataka',pin:'5600'+Math.floor(R()*80+10)}:null,branch:b.id,pay:['UPI','Card','COD'][Math.floor(R()*3)],status:'new',created:Date.now(),stageAt:Date.now(),note:R()>.6?'Extra napkins please':'',auto:false,seed:true,mine:false,pts:0};
  S.orders.unshift(o);save();toast('New order #'+o.id+' received','ok');emit('orders');refreshAdmin()};
/* ----- products ----- */
const defArt={pizza:['pizza','cheese'],burgers:['burger','veg'],fries:['fries','classic'],wraps:['wrap','v'],sides:['side','nuggets'],beverages:['cup','mojito'],desserts:['dessert','lava'],combos:['combo','solo']};
const sw=(on,act,id,label)=>`<button class="switch ${on?'on':''}" role="switch" aria-checked="${on}" aria-label="${label}" data-act="${act}" data-id="${id}"><i></i></button>`;
ADM.products=()=>{const l=S.products.filter(p=>!PS||(p.name+p.cat).toLowerCase().includes(PS.toLowerCase()));
  return`<div class="row between wrap-r"><form class="search sm" data-form="noop" role="search"><span class="s-ic">${ic('search')}</span><label class="sr" for="psearch">Search products</label><input id="psearch" type="search" placeholder="Search products" value="${esc(PS)}"></form><div class="row wrap-r"><button class="btn ghost sm" data-act="catMgr">Categories</button><button class="btn ghost sm" data-act="topMgr">Toppings</button><button class="btn red sm" data-act="pForm">${ic('plus')} Add product</button></div></div><section class="co-card"><div class="tbl-w"><table class="tbl"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Bestseller</th><th>Out of stock</th><th><span class="sr">Actions</span></th></tr></thead><tbody>${l.map(p=>`<tr><td><div class="pt"><span class="pt-a">${media(p)}</span><span><b>${esc(p.name)}</b><small>${vm(p.veg)} ${p.cust?'Customisable':''}</small></span></div></td><td>${catOf(p.cat).emoji} ${catOf(p.cat).name}</td><td><b>${inr(p.price)}</b>${p.mrp>p.price?`<small><s>${inr(p.mrp)}</s></small>`:''}</td><td><div class="qty sm"><button data-act="stock" data-id="${p.id}" data-d="-1" aria-label="Decrease stock for ${esc(p.name)}">${ic('minus')}</button><output>${p.stock}</output><button data-act="stock" data-id="${p.id}" data-d="1" aria-label="Increase stock for ${esc(p.name)}">${ic('plus')}</button></div></td><td>${sw(p.tag==='best',  'pBest',p.id,'Bestseller: '+p.name)}</td><td>${sw(p.oos,'pOos',p.id,'Out of stock: '+p.name)}</td><td class="act-c"><button class="btn ghost sm" data-act="pForm" data-id="${p.id}">${ic('edit')} Edit</button><button class="btn ghost sm danger" data-act="pDel" data-id="${p.id}" aria-label="Delete ${esc(p.name)}">${ic('trash')}</button></td></tr>`).join('')}</tbody></table></div></section>`};
document.addEventListener('input',e=>{if(e.target.id==='psearch'){PS=e.target.value;const p=e.target.selectionStart;$('#adm-body').innerHTML=ADM.products();const n=$('#psearch');n.focus();n.setSelectionRange(p,p)}});
const refreshProducts=()=>{if(route().name==='admin'&&route().seg[0]==='products'){const p=$('#adm-body').scrollTop;$('#adm-body').innerHTML=ADM.products()}};
A.stock=b=>{const p=prod(b.dataset.id);p.stock=Math.max(0,p.stock+ +b.dataset.d);save();refreshProducts()};
A.pBest=b=>{const p=prod(b.dataset.id);p.tag=p.tag==='best'?'':'best';p.bestseller=p.tag==='best';save();refreshProducts();toast(p.name+(p.tag==='best'?' marked as bestseller':' removed from bestsellers'),'ok')};
A.pOos=b=>{const p=prod(b.dataset.id);p.oos=!p.oos;save();refreshProducts();toast(p.name+(p.oos?' marked out of stock':' back in stock'),'ok')};
A.pDel=b=>{const p=prod(b.dataset.id);confirmBox('Delete '+p.name+'?','It will be removed from the menu. Past orders keep their history.','Delete product',()=>{S.products=S.products.filter(x=>x.id!==p.id);S.cart=S.cart.filter(l=>l.pid!==p.id);save();refreshProducts();toast('Product deleted','ok')})};
let PIMG=null;
A.pForm=b=>{const id=b.dataset.id,p=id?prod(id):{name:'',cat:S.cats[0].id,veg:1,price:'',mrp:'',spice:0,stock:30,desc:'',ing:[],cust:'',tag:''};PIMG=p.img||null;
  openLayer(`<div class="dr-h"><h2>${id?'Edit':'Add'} product</h2><button class="x-btn" data-act="closeLayer" aria-label="Close">${ic('x')}</button></div><form class="pad form" data-form="product" data-id="${id||''}" novalidate>${field({id:'fn',label:'Product name',req:1,value:p.name})}<div class="g2"><div class="fld"><label for="fc">Category</label><select id="fc">${S.cats.map(c=>`<option value="${c.id}" ${c.id===p.cat?'selected':''}>${c.emoji} ${c.name}</option>`).join('')}</select></div><div class="fld"><label for="fv">Diet</label><select id="fv"><option value="1" ${p.veg?'selected':''}>Vegetarian</option><option value="0" ${p.veg?'':'selected'}>Non-vegetarian</option></select></div></div><div class="g3">${field({id:'fp',label:'Price (₹)',req:1,type:'number',value:p.price,mode:'numeric'})}${field({id:'fm',label:'Original price (₹)',type:'number',value:p.mrp>p.price?p.mrp:'',hint:'Optional, shows discount'})}${field({id:'fs',label:'Stock',type:'number',value:p.stock,req:1})}</div><div class="g3"><div class="fld"><label for="fsp">Spice level</label><select id="fsp">${[0,1,2,3].map(n=>`<option value="${n}" ${p.spice===n?'selected':''}>${['Not spicy','Mild','Medium','Hot'][n]}</option>`).join('')}</select></div><div class="fld"><label for="fcu">Customisation</label><select id="fcu"><option value="" ${!p.cust?'selected':''}>None</option><option value="pizza" ${p.cust==='pizza'?'selected':''}>Pizza options</option><option value="burger" ${p.cust==='burger'?'selected':''}>Burger options</option></select></div><div class="fld"><label for="ft">Badge</label><select id="ft"><option value="" ${!p.tag?'selected':''}>None</option><option value="best" ${p.tag==='best'?'selected':''}>Bestseller</option><option value="new" ${p.tag==='new'?'selected':''}>New</option></select></div></div><div class="fld"><label for="fd">Description</label><textarea id="fd" rows="2" maxlength="180">${esc(p.desc)}</textarea><span class="err" id="fd-e" role="alert"></span></div>${field({id:'fi',label:'Ingredients / toppings',value:p.ing.join(', '),hint:'Separate with commas'})}<div class="fld"><label for="fimg">Product image</label><div class="img-up"><span class="pt-a" id="fimg-p">${PIMG?`<img src="${PIMG}" alt="Product preview">`:'<small>Illustration</small>'}</span><input id="fimg" type="file" accept="image/*"><button type="button" class="txt-btn danger" data-act="imgClear">Remove</button></div></div><button class="btn red block lg" type="submit">${id?'Save changes':'Add product'}</button></form>`,{kind:'sheet',cls:'sm',label:'Product form'})};
document.addEventListener('change',async e=>{if(e.target.id==='fimg'&&e.target.files[0]){try{PIMG=await readImage(e.target.files[0],420);$('#fimg-p').innerHTML=`<img src="${PIMG}" alt="Product preview">`}catch(x){toast(x.message,'error')}}});
A.imgClear=()=>{PIMG=null;$('#fimg-p').innerHTML='<small>Illustration</small>';$('#fimg').value=''};
FORMS.product=f=>{if(!checkForm(f,[['fn',v=>v.length>1,'Enter a product name.'],['fp',v=>+v>0,'Enter a price above ₹0.'],['fs',v=>v!==''&&+v>=0,'Enter the stock count.'],['fd',v=>v.length>=10,'Add a short description (10+ characters).']]))return;
  const id=f.dataset.id,c=$('#fc').value,d={name:f.fn.value.trim(),cat:c,veg:+$('#fv').value,price:+f.fp.value,mrp:+f.fm.value||+f.fp.value,stock:+f.fs.value,spice:+$('#fsp').value,cust:$('#fcu').value,tag:$('#ft').value,desc:$('#fd').value.trim(),ing:f.fi.value.split(',').map(x=>x.trim()).filter(Boolean),img:PIMG||''};d.bestseller=d.tag==='best';
  if(id){const p=prod(id);Object.assign(p,d);if(d.cust==='burger'&&!p.dpat)p.dpat=p.veg?'aloo':'cchick'}else{S.products.unshift({id:'x'+uid(),art:defArt[c]||['side','nuggets'],dpat:d.cust==='burger'?(d.veg?'aloo':'cchick'):'',sold:0,rating:4.5,rev:0,oos:false,created:Date.now(),...d})}
  save();closeLayer(f.closest('.layer'));refreshProducts();toast(id?'Product updated':'Product added','ok')};
A.catMgr=()=>{const el=openLayer(catMgrHTML(),{kind:'sheet',cls:'sm',label:'Manage categories'})};
const catMgrHTML=()=>`<div class="dr-h"><h2>Categories</h2><button class="x-btn" data-act="closeLayer" aria-label="Close">${ic('x')}</button></div><div class="pad"><ul class="mgr">${S.cats.map(c=>`<li><span>${c.emoji}</span><b>${esc(c.name)}</b><small>${S.products.filter(p=>p.cat===c.id).length} items</small><button class="txt-btn danger" data-act="catDel" data-id="${c.id}" aria-label="Delete ${esc(c.name)}">${ic('trash')}</button></li>`).join('')}</ul><form class="form" data-form="cat" novalidate><div class="g2">${field({id:'cne',label:'Emoji',value:'🍽️',max:4})}${field({id:'cnn',label:'Category name',req:1})}</div><button class="btn red block" type="submit">Add category</button></form></div>`;
FORMS.cat=f=>{if(!checkForm(f,[['cnn',v=>v.length>1,'Enter a category name.']]))return;const n=f.cnn.value.trim();S.cats.push({id:slug(n),name:n,emoji:f.cne.value||'🍽️'});save();$('.panel',f.closest('.layer')).innerHTML=catMgrHTML();toast('Category added','ok')};
A.catDel=b=>{const n=S.products.filter(p=>p.cat===b.dataset.id).length;if(n){toast('Move or delete its '+n+' products first.','warn');return}S.cats=S.cats.filter(c=>c.id!==b.dataset.id);save();$('.panel',b.closest('.layer')).innerHTML=catMgrHTML();toast('Category deleted','ok')};
const topMgrHTML=()=>`<div class="dr-h"><h2>Toppings & extras</h2><button class="x-btn" data-act="closeLayer" aria-label="Close">${ic('x')}</button></div><div class="pad"><p class="muted small">Custom toppings appear in the customisation screen for pizzas or burgers.</p><ul class="mgr">${S.xtops.length?S.xtops.map(t=>`<li><span>➕</span><b>${esc(t.name)}</b><small>${t.cust} · ${inr(t.price)}</small><button class="txt-btn danger" data-act="topDel" data-id="${t.id}" aria-label="Delete ${esc(t.name)}">${ic('trash')}</button></li>`).join(''):'<li class="muted">No custom toppings yet.</li>'}</ul><form class="form" data-form="top" novalidate><div class="g3">${field({id:'tn',label:'Topping name',req:1})}${field({id:'tpr',label:'Price (₹)',type:'number',req:1,value:'30'})}<div class="fld"><label for="tcu">For</label><select id="tcu"><option value="pizza">Pizza</option><option value="burger">Burger</option></select></div></div><button class="btn red block" type="submit">Add topping</button></form></div>`;
A.topMgr=()=>openLayer(topMgrHTML(),{kind:'sheet',cls:'sm',label:'Manage toppings'});
FORMS.top=f=>{if(!checkForm(f,[['tn',v=>v.length>1,'Enter a topping name.'],['tpr',v=>+v>=0&&v!=='','Enter a price.']]))return;S.xtops.push({id:'x'+uid(),name:f.tn.value.trim(),price:+f.tpr.value,cust:$('#tcu').value});save();$('.panel',f.closest('.layer')).innerHTML=topMgrHTML();toast('Topping added','ok')};
A.topDel=b=>{S.xtops=S.xtops.filter(t=>t.id!==b.dataset.id);save();$('.panel',b.closest('.layer')).innerHTML=topMgrHTML()};
/* ----- offers ----- */
ADM.offers=()=>`<section class="co-card"><h2>Create coupon</h2><form class="form" data-form="cpn" novalidate><div class="g4">${field({id:'kc',label:'Code',req:1,ph:'SUMMER15',max:14})}<div class="fld"><label for="kt">Type</label><select id="kt"><option value="pct">Percent off</option><option value="flat">Flat ₹ off</option><option value="ship">Free delivery</option></select></div>${field({id:'kv',label:'Discount value',type:'number',value:'10',hint:'% or ₹, ignored for free delivery'})}${field({id:'km',label:'Minimum order (₹)',type:'number',value:'199'})}</div><div class="g4">${field({id:'kx',label:'Max discount (₹)',type:'number',value:'100',hint:'For percent coupons'})}${field({id:'ke',label:'Expires on',type:'date',req:1,value:new Date(Date.now()+30*DAY).toISOString().slice(0,10)})}</div><button class="btn red" type="submit">Create coupon</button></form></section>
  <section class="co-card"><div class="row between"><h2>Coupons</h2></div><div class="tbl-w"><table class="tbl"><thead><tr><th>Code</th><th>Offer</th><th>Min order</th><th>Expires</th><th>Active</th><th><span class="sr">Actions</span></th></tr></thead><tbody>${S.coupons.map(c=>{const ex=new Date(c.exp+'T23:59:59')<new Date();return`<tr><td><b>${esc(c.code)}</b>${ex?'<small class="bad-t">Expired</small>':''}</td><td>${c.type==='pct'?c.value+'% off'+(c.max?' (up to '+inr(c.max)+')':''):c.type==='flat'?inr(c.value)+' off':'Free delivery'}</td><td>${inr(c.min)}</td><td>${fmtDate(new Date(c.exp))}</td><td>${sw(c.active,'cToggle',c.code,'Active: '+c.code)}</td><td class="act-c"><button class="btn ghost sm" data-act="cNotify" data-id="${c.code}">${ic('bell')} Notify</button><button class="btn ghost sm danger" data-act="cDel" data-id="${c.code}" aria-label="Delete ${esc(c.code)}">${ic('trash')}</button></td></tr>`}).join('')}</tbody></table></div></section>`;
FORMS.cpn=f=>{if(!checkForm(f,[['kc',v=>/^[A-Za-z0-9]{4,14}$/.test(v),'Use 4–14 letters or numbers, no spaces.'],['ke',v=>v&&new Date(v+'T23:59:59')>new Date(),'Pick a future expiry date.']]))return;const code=f.kc.value.trim().toUpperCase(),t=$('#kt').value;if(coupon(code)){$('#kc-e').textContent='That code already exists.';return}
  if(t==='pct'&&(+f.kv.value<1||+f.kv.value>90)){$('#kv-e').textContent='Percent must be between 1 and 90.';return}
  S.coupons.unshift({code,type:t,value:+f.kv.value||0,min:+f.km.value||0,max:t==='pct'?+f.kx.value||0:0,exp:f.ke.value,active:true,desc:(t==='pct'?f.kv.value+'% off':t==='flat'?'Flat ₹'+f.kv.value+' off':'Free delivery')+(f.km.value>0?' on orders above ₹'+f.km.value:'')});save();$('#adm-body').innerHTML=ADM.offers();toast('Coupon '+code+' created','ok')};
A.cToggle=b=>{const c=coupon(b.dataset.id);c.active=!c.active;save();$('#adm-body').innerHTML=ADM.offers();if(!c.active&&S.coupon===c.code){S.coupon='';refreshCart()}};
A.cDel=b=>confirmBox('Delete coupon '+b.dataset.id+'?','Customers will no longer be able to use it.','Delete',()=>{S.coupons=S.coupons.filter(c=>c.code!==b.dataset.id);if(S.coupon===b.dataset.id)S.coupon='';save();$('#adm-body').innerHTML=ADM.offers();refreshCart()});
A.cNotify=b=>{const c=coupon(b.dataset.id);notify('coupon','Coupon reminder: '+c.code,c.desc+'. Apply it in your cart.','#/offers/codes');toast('Notification sent to customers','ok')};
/* ----- customers ----- */
ADM.customers=()=>{const real=S.users.map(u=>{const os=S.orders.filter(o=>o.uid===u.id&&o.status!=='rejected');return{n:u.name,ph:u.phone,c:os.length+(u.id==='u_demo'?9:0),s:os.reduce((a,o)=>a+o.total,0)+(u.id==='u_demo'?3800:0),last:os[0]?os[0].created:u.created,p:u.pts,t:tierOf(u.life).n}});
  const seed=SEED_CUST.map(([n,ph,c,s,d,p])=>({n,ph,c,s,last:Date.now()-d*DAY,p,t:tierOf(p*1.4).n})),all=[...real,...seed].sort((a,b)=>b.s-a.s);
  return`<section class="co-card"><div class="tbl-w"><table class="tbl"><thead><tr><th>Customer</th><th>Orders</th><th>Total spending</th><th>Last order</th><th>Loyalty points</th><th>Level</th></tr></thead><tbody>${all.map(c=>`<tr><td><div class="pt">${avatar(c.n,'#'+(hash(c.n)%0x9A9A9A+0x300000).toString(16).slice(0,6).padStart(6,'3'))}<span><b>${esc(c.n)}</b><small>${esc(c.ph)}</small></span></div></td><td>${c.c}</td><td><b>${inr(c.s)}</b></td><td>${ago(c.last)}</td><td>${c.p.toLocaleString('en-IN')}</td><td><span class="pill tier-${c.t}">${c.t}</span></td></tr>`).join('')}</tbody></table></div></section><section class="co-card"><h2>Messages & subscribers</h2><p class="muted">${S.subs.length} newsletter subscriber${S.subs.length===1?'':'s'} and ${S.msgs.length} message${S.msgs.length===1?'':'s'} from this site.</p>${S.msgs.length?`<ul class="msgs">${S.msgs.slice(0,6).map(m=>`<li><b>${esc(m.name)}</b> <small>${ago(m.ts)}</small><p>${esc(m.text)}</p></li>`).join('')}</ul>`:''}</section>`};
/* ----- reviews ----- */
ADM.reviews=()=>{const all=Object.entries(S.reviews).flatMap(([pid,l])=>l.map(r=>({...r,pid}))).sort((a,b)=>b.ts-a.ts).slice(0,60);
  return`<section class="co-card"><div class="tbl-w"><table class="tbl"><thead><tr><th>Review</th><th>Product</th><th>Rating</th><th>Status</th><th><span class="sr">Actions</span></th></tr></thead><tbody>${all.map(r=>`<tr><td class="rv-c"><b>${esc(r.name)}</b> ${r.verified?`<span class="ver">${ic('check')} Verified</span>`:''}<small>${ago(r.ts)}</small><p>${esc(r.text)}</p>${r.img?`<img class="rv-img sm" src="${r.img}" alt="Customer photo">`:''}</td><td>${esc(prod(r.pid)?.name||'Removed item')}</td><td>${starRow(r.rating)}</td><td><span class="pill ${r.hidden?'st-rejected':'st-delivered'}">${r.hidden?'Hidden':'Published'}</span></td><td class="act-c"><button class="btn ghost sm" data-act="rvHide" data-id="${r.id}" data-p="${r.pid}">${r.hidden?'Publish':'Hide'}</button><button class="btn ghost sm danger" data-act="rvDel" data-id="${r.id}" data-p="${r.pid}" aria-label="Delete review">${ic('trash')}</button></td></tr>`).join('')}</tbody></table></div></section>`};
A.rvHide=b=>{const r=S.reviews[b.dataset.p].find(x=>x.id===b.dataset.id);r.hidden=!r.hidden;save();$('#adm-body').innerHTML=ADM.reviews();toast(r.hidden?'Review hidden from customers':'Review published','ok')};
A.rvDel=b=>confirmBox('Delete this review?','This can’t be undone.','Delete',()=>{S.reviews[b.dataset.p]=S.reviews[b.dataset.p].filter(x=>x.id!==b.dataset.id);save();$('#adm-body').innerHTML=ADM.reviews()});
/* ----- analytics ----- */
ADM.analytics=()=>{const h=salesHist(),rg=AN.range;let vals,labels,title;
  if(rg==='daily'){const l=h.slice(-14);vals=l.map(d=>d.sales);labels=l.map(d=>dl(d.ts));title='Daily sales · last 14 days'}
  else if(rg==='weekly'){vals=[];labels=[];for(let w=7;w>=0;w--){const s=h.slice(365-(w+1)*7,365-w*7);vals.push(s.reduce((a,d)=>a+d.sales,0));labels.push(dl(s[0].ts))}title='Weekly sales · last 8 weeks'}
  else{vals=[];labels=[];for(let m=11;m>=0;m--){const s=h.slice(Math.max(0,365-(m+1)*30),365-m*30);vals.push(s.reduce((a,d)=>a+d.sales,0));labels.push(dl(s[s.length-1].ts))}title='Monthly sales · last 12 months'}
  const top=[...S.products].sort((a,b)=>b.sold-a.sold).slice(0,8).map(p=>[p.name,p.sold]),cs={};S.products.forEach(p=>cs[p.cat]=(cs[p.cat]||0)+p.sold);const cats=Object.entries(cs).sort((a,b)=>b[1]-a[1]).map(([c,v])=>[catOf(c).name,v]);
  const l30=h.slice(-30),ma=l30.map((_,i)=>{const w=h.slice(365-30+i-6,365-30+i+1);return w.reduce((a,d)=>a+d.sales,0)/w.length});
  const cg=Array.from({length:12},(_,i)=>Math.round(3400+i*640+(i>9?(i-9)*90:0))+(i===11?S.users.length-1:0)),cgl=Array.from({length:12},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-(11-i));return d.toLocaleDateString('en-IN',{month:'short'})});
  return`<div class="adm-grid one"><section class="co-card"><div class="row between wrap-r"><h2>${title}</h2><div class="chips" role="tablist">${[['daily','Daily'],['weekly','Weekly'],['monthly','Monthly']].map(([k,l])=>`<button class="chip sm ${rg===k?'on':''}" role="tab" aria-selected="${rg===k}" data-act="anRange" data-r="${k}">${l}</button>`).join('')}</div></div>${barChart(vals,labels)}</section></div>
  <div class="adm-grid"><section class="co-card"><h2>Best-selling products</h2>${hbar(top)}</section><section class="co-card"><h2>Most ordered categories</h2>${donut(cats)}</section></div>
  <div class="adm-grid"><section class="co-card"><h2>Revenue trend · 30 days</h2>${lineChart([{vals:l30.map(d=>d.sales),color:'#FF7A1A',area:1,thin:1},{vals:ma,color:'#B4121B'}],l30.map(d=>dl(d.ts)))}<p class="muted small"><i class="lg-d" style="background:#FF7A1A"></i>Daily <i class="lg-d" style="background:#B4121B"></i>7-day average</p></section><section class="co-card"><h2>Customer growth</h2>${lineChart([{vals:cg,color:'#1E9E4A',area:1,dots:1}],cgl,v=>Math.round(v).toLocaleString('en-IN'))}</section></div>`};
A.anRange=b=>{AN.range=b.dataset.r;$('#adm-body').innerHTML=ADM.analytics()};
function refreshAdmin(){if(route().name!=='admin'||!S.adminAuth)return;const a=document.activeElement;if(a&&a.closest('#adm-body')&&/INPUT|TEXTAREA|SELECT/.test(a.tagName))return;if(layers.length)return;const sec=route().seg[0]||'overview';if(!['overview','orders'].includes(sec))return;const b=$('#adm-body');if(b){const y=window.scrollY;b.innerHTML=ADM[sec]();window.scrollTo(0,y)}const c=$('.adm-side nav a[href$=orders] .cnt');}
on('orders',refreshAdmin);
/* ----- Kitchen display ----- */
const KCOLS=[['new','New',s=>['new','confirmed'].includes(s)],['preparing','Preparing',s=>s==='preparing'],['ready','Ready',s=>s==='ready'],['done','Completed',s=>['out','delivered'].includes(s)]];
function kcCard(o,col){
  const act={new:o.status==='new'?`<button class="btn ghost sm danger" data-act="kReject" data-id="${o.id}">Reject</button><button class="btn orange sm" data-act="kAdv" data-id="${o.id}">Accept & start</button>`:`<button class="btn orange sm" data-act="kAdv" data-id="${o.id}">Start cooking</button>`,preparing:`<button class="btn orange sm" data-act="kAdv" data-id="${o.id}">Mark ready</button>`,ready:`<button class="btn orange sm" data-act="kAdv" data-id="${o.id}">${o.type==='pickup'?'Handed over':'Send with rider'}</button>`,done:`<span class="muted small">${STATUS_LABEL[o.status]} ${ago(o.stageAt)}</span>`}[col];
  return`<article class="kc ${col}" data-late="0"><header><b>#${o.id.replace('EC-','')}</b><span class="pill k-${o.type}">${o.type==='pickup'?'Pickup':'Delivery'}</span>${col!=='done'?`<span class="k-t" title="Time since order placed">${ic('clock')}<span data-since="${o.created}">0:00</span></span>`:''}</header><ul>${o.items.map(i=>`<li><b>${i.qty}×</b><span>${esc(i.name)}${i.summary?`<small>${esc(i.summary)}</small>`:''}${i.instr?`<em>“${esc(i.instr)}”</em>`:''}</span></li>`).join('')}</ul>${o.note?`<p class="k-note">${ic('info')} ${esc(o.note)}</p>`:''}<footer><small>${esc(o.cust.name.split(' ')[0])}</small><div class="row">${act}</div></footer></article>`}
PAGES.kitchen=()=>{setMeta('Kitchen display | Ember & Crust','');if(!S.adminAuth)return PAGES.admin({seg:[]});return kdsHTML()};
function kdsHTML(){const t0=dayStart();const cols=KCOLS.map(([k,n,f])=>{let l=S.orders.filter(o=>f(o.status)&&o.created>=t0-DAY);if(k==='done')l=l.slice(0,6);else l=l.slice().sort((a,b)=>a.created-b.created);return`<section class="kcol ${k}" aria-label="${n}"><h2>${n} <b>${l.length}</b></h2><div class="kcol-b">${l.map(o=>kcCard(o,k)).join('')||`<p class="muted center">Nothing here</p>`}</div></section>`}).join('');
  return`<div class="kds"><header class="kds-top"><div class="row"><a class="btn ghost-l sm" href="#/admin/orders">← Dashboard</a><h1>Kitchen display</h1></div><div class="row"><span class="kds-clock" id="kclock"></span><label class="tgl sm"><input type="checkbox" id="autoT" ${S.auto?'checked':''}><span class="tgl-t">Demo auto-progress</span></label><button class="btn orange sm" data-act="simOrder">${ic('plus')} Simulate order</button></div></header><div class="kds-cols" id="kds-cols">${cols}</div></div>`}
AFTER.kitchen=()=>{const c=()=>{const e=$('#kclock');if(e)e.textContent=new Date().toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit',second:'2-digit'})};c();timers.push(setInterval(c,1000))};
on('orders',()=>{if(route().name==='kitchen'&&S.adminAuth){const b=$('#kds-cols');if(b){const y=b.scrollLeft;b.parentElement.outerHTML=kdsHTML();$('#kds-cols').scrollLeft=y;tickCd()}}});
A.kAdv=b=>{const o=order(b.dataset.id);o.auto=false;if(o.status==='new'){setStatus(o,'confirmed');setStatus(o,'preparing');return}const nx=nextStatus(o);if(nx)setStatus(o,nx)};
A.kReject=b=>{const o=order(b.dataset.id);o.auto=false;setStatus(o,'rejected')};
